### ISSUE TITLE
Custom State not showing any data when deployed in Azure App Services.

### ISSUE THREAD

**Issue by ilanopat** [OfficeDev/BotBuilder-MicrosoftTeams#100]
I'm saving a state from a result coming from API request on third-party API. When I access it using Dialog Context, it's not showing.

**Comment by billbliss** [comment]
What state provider are you using?

**Comment by ilanopat** [comment]
Azure SQL

**Comment by RamjotSingh** [comment]
Extension SDK does not deal with data storage (or Dialogs for that matter). Did you try asking BotFramework folks at https://github.com/Microsoft/BotBuilder

**Comment by ilanopat** [comment]
Okay I see, I actually asked them before about the custom state, if it can be accessed inside Dialogs they said yes and through context but it's during my debugging on localhost. And I saw different results from when I access it through the scope and through dialogs (btw I'm using IBotDataStore), I guess I'm just gonna ask them now that I'm hosting it on Azure.
