### ISSUE TITLE
Prompts.choice() dont work for voice client HK Invoke 

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#101]
I have been trying to get the answer since long. I had posted it here [*] so thought I will have have better luck if I post here. 

*
https://social.msdn.microsoft.com/Forums/en-US/db25e4e6-8a9c-4e4d-a17a-588551175914/choice-prompts-dont-work-with-cortana-voice-clients?forum=cortanaskillskit

**Comment by RamjotSingh** [comment]
This repo deals with Microsoft Team alone. Try asking on Microsoft Bot Builder repo here https://github.com/Microsoft/BotBuilder
