### ISSUE TITLE
BOT stopped working in MS teams.

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#103]
I have a BOT with MS teams channel that is migrated from BF portal to azure couple of weeks back. It has Azure web app running behind where code is deployed. I manage all Bot settings in Azure now as on 31st March BF portal might go away. So far until 28th March my bot in MS teams was working fine. I have a screenshot attached. 
This is enterprise level bot which will be used by almost 25k people and its currently under Non-prod UAT testing. The way I ask users to interact with is by sharing following link. 

[https://teams.microsoft.com/l/chat/0/0?users=28:{BOTID](https://teams.microsoft.com/l/chat/0/0?users=28:{BOTID})

Yesterday, I flipped the messaging endpoint URL to my local Ngrok url to test something. After that I realized BOT isn't responding in teams. I can confirm azure app service is running and I can test in 'Test we Chat window'. I even have Cortana channel working with same bot. If I flip the url back to azure endpoint still doesnt work. MS teams 100& stopped working. I tried with 2 more bots. No luck.

1. Is it possible massage URL flip caused something ? 
2. How can I debug the issue ?
3. Is it possible BOT+teams configuration is cached somewhere so can we clear it ? So it starts working. 

![image](https://user-images.githubusercontent.com/32375467/38150253-a16811e4-3423-11e8-854e-9cbdd2105242.png)

![image](https://user-images.githubusercontent.com/32375467/38150257-a599a566-3423-11e8-848a-014b9940baf4.png)

**Comment by billbliss** [comment]
Try changing the endpoint again - even if it's to the same thing - and try again. Over the past few days we've had a live site incident in the system that connects Bot Framework and Skype (which powers the back end of Teams).

**Comment by rjgmail88** [comment]
I did try several times but did not work. Based on your response looks like it is backend issue. Any suggestions ? Can you please update here once its back up ? 
Thanks

**Comment by billbliss** [comment]
Did you try just now? It should have been fixed by about noon Pacific time. If not, what's your bot ID?

**Comment by rjgmail88** [comment]
@billbliss , I did try with another BOT and its working but the one I mentioned in the screenshot is still . not. Here is the bot ID bc6873dc-1736-40be-98cc-b55df64647b4

**Comment by Wajeed-msft** [comment]
@rjgmail88 : Could you please try updating the endpoint once more and let us know?

**Comment by rjgmail88** [comment]
Sure, I will update soon on this.

**Comment by rjgmail88** [comment]
@Wajeed-msft bot ID bc6873dc-1736-40be-98cc-b55df64647b4 is working now.I am facing one more issue where Bot display name is not getting updated. I changed the bot name on dev bot portal. 
Let me know if I should open a new issue .

**Comment by Wajeed-msft** [comment]
@rjgmail88 Glad to know that your issue is resolved. 
Regarding the bot's name, I could see your bot name as "Gina Demo Bot". What is the bot name that you have set?
Could you please try your bot from a different user account? There is a possiblity that bot name is cached.

**Comment by rjgmail88** [comment]
@Wajeed-msft , I confirmed for new users it is showing correct/expected name.

**Comment by billbliss** [comment]
Once an app is in the AppSource store (what appears in the "Store" icon in Teams, the name there takes precedence. If it's been sideloaded by users, the cached bot name takes precedence. There's no way to force an update other than the AppSource directory.

**Comment by rjgmail88** [comment]
I haven't side loaded these bots and used following link to access it. Not sure if its called side-loading.  
teams.microsoft.com/l/chat/0/0?users=28:{botID}

I just confirmed bot the bots mentioned above are not part of a MS Store. What is AppSource directory ? and there is not way to force name update ? I can open support ticket with Microsoft if needed. We have premier support.

**Comment by rjgmail88** [comment]
@Wajeed-msft could you update us this please ?

**Comment by billbliss** [comment]
The URL you are using is a form of sideloading.

**Comment by rjgmail88** [comment]
Thanks @billbliss , so there is no absolute way to fix the name? Not in the future too ?

**Comment by wsoula** [comment]
Is this true that once you create a bot in azure you can not change anything about it without creating a new bot?

**Comment by wsoula** [comment]
I dont think my issue was related to this at all and I was hoping my understanding was wrong and it was, changing the name is fine.
