### ISSUE TITLE
Autocompletion feature for bot commands, like "Who"-Bot in MS Teams

### ISSUE THREAD

**Issue by serialoverflow** [OfficeDev/BotBuilder-MicrosoftTeams#105]
The "Who"-Bot in Microsoft Teams is implementing a very useful autocompletion feature for Bot commands. 
Here is how it looks:
![screen shot 2018-04-13 at 14 18 47](https://user-images.githubusercontent.com/279131/38734368-aba6533e-3f25-11e8-8a73-aa42071d59a2.png)
![screen shot 2018-04-13 at 14 19 02](https://user-images.githubusercontent.com/279131/38734369-abbe4a8e-3f25-11e8-8c61-5f5886f3e37c.png)

Sadly, I don't see any way to do this currently, with any of the ChatConnectors or MS Teams libraries. Is there a way to use this? If not, would you consider implementing/exposing it?
Thank you!

**Comment by RamjotSingh** [comment]
Please refer to https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-menus

**Comment by serialoverflow** [comment]
Thank you for the quick response and sorry about wasting your time. I should have found that in the documentation.
