### ISSUE TITLE
List Card not found

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#111]
Hi,

Could you please add samples so that we could try out
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#list-card

Also i was unable to find the same in botbuilder-teams.d.js. Where is it defined ?

Thanks

**Comment by register9091** [comment]
Could you please provide an example on how to use the JSON manually ? Or could you please refer me to an example.

**Comment by register9091** [comment]
Thank you. Got it working. 

List Card is not supported in Bot Emulator ?

**Comment by billbliss** [comment]
That's correct - it only works in Teams.
