### ISSUE TITLE
Support for scrollable cards in ListCard

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#123]
Hi,

Is it possible to add say adaptive / hero cards to as a list item in list card? Is yes, how else is this feature in the pipeline?

Thanks

**Comment by billbliss** [comment]
By list card, you mean https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#list-card? 

That is its own format; it's not miniaturized view of other cards. There are no current plans to have lists of adaptive cards but once we release that (it's in developer preview now) we might consider it.

**Comment by register9091** [comment]
Ok thanks
