### ISSUE TITLE
Feature Request: Adaptive cards Action.ShowCard toggle text and default expansion state

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#129]
Hi,

I would like to request the following features for Adaptive cards -> Action ShowCard button for MS teams.

1. Option to show card in an expanded state.
Reason: We are updating the card when the user clicks on show more details which leads to the user having to click the card twice, to see the details.
Known workaround: Render an expanded card with another Hide details button and do a call to the backend to update the card to collapsed state.

2. Option to set toggle text for ShowCard button
Reason: Say a user clicks on show details then the button should change to hide details itself. Especially helpful if you want to avoid backend calls.
Known workaround: Same as above.

Kindly consider these features for implementation.

Thanks

**Comment by billbliss** [comment]
All feature requests for Adaptive Cards are handled centrally here: https://github.com/Microsoft/AdaptiveCards/issues. Please add 1 and 2 above as separate issues. 

The first one you're asking may be [contentious](https://github.com/Microsoft/AdaptiveCards/issues/495) but I'm not sure what you are asking for is the same thing -- but they are pretty responsive and you'll probably find out fairly quickly.

FYI here's the [Adaptive Cards vNext feature list](https://github.com/Microsoft/AdaptiveCards/wiki/1.1-Feature-List).
