### ISSUE TITLE
MicrosoftTeams channel doesn't recognize URL's  

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#130]
I have QnA BOT which is using MS team channel. When QnA has an answer which contains URL I see it's clickable in emulator but not in teams. I feel like teams isn't able recognize url's from text.
Here are the screenshots. 

MS teams

![image](https://user-images.githubusercontent.com/32375467/42103048-7e4f428e-7b8d-11e8-8bd5-d62c545a196f.png)

Emulator

![image](https://user-images.githubusercontent.com/32375467/42103049-809428f2-7b8d-11e8-9016-00eac277fe85.png)

Is there any limitation on Ms teams channel ?

**Comment by register9091** [comment]
I cannot comment about limitations but you could use text forgetting to get it working in teams. It works fine.

**Comment by arun-msft** [comment]
The auto hyperlinking in Teams is done on the client in our editor so the only way to do it in bots is via markdown. Here is the sample code
 var reply=activity.CreateReply(@"[Bing](https://www.bing.com/)");
 reply.TextFormat = TextFormatTypes.Markdown;
await connector.Conversations.ReplyToActivityWithRetriesAsync(reply);

**Comment by billbliss** [comment]
Yes, that's the way to do it, @arun-msft, but your example is more complicated than it needs to be, and TextFormatTypes.Markdown is the default, so you can just do this to create a link to this issue:

`await connector.Conversations.ReplyToActivityWithRetriesAsync("[This issue](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/130)");`

Will insert this into the chat stream:

[This issue](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/130)
