### ISSUE TITLE
Deleting bot chat conversation

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#132]
Hi,

Is it possible to delete bot 1-1 / personal conversation with user using [bot state API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-state?view=azure-bot-service-3.0#delete-user-data)

If yes then the URL endpoint  `DELETE /v3/botstate/{channelId}/users/{userId} `
returns a 404 for channel id = msteams and userid = OUR_USER_ID

And yes i have seen [this](https://support.office.com/en-us/article/delete-a-chat-in-teams-da6d87ed-59bc-4407-9291-95ee193f8344), just wanted to confirm.
Thanks

**Comment by Wajeed-msft** [comment]
@register9091 - The [Bot State APIs](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-state?view=azure-bot-service-3.0) are used to store and retrieve state data and not the chat thread/conversation. Currently, there is only [Create Chat Thread api](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/chatthread) available in beta version.

**Comment by register9091** [comment]
@Wajeed-msft is there any alternate way to delete the conversations? Or say keep it in memory only for the current session? Maybe a url flag?

We need this for testing purposes.

**Comment by aosolis** [comment]
The conversation itself cannot be deleted: once a conversation is established between a user and a bot the same "thread" will be used each time. However, if you're referring to the bot state you're storing against the conversation, you can use an in-memory store. See examples [Node](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/7d6c7b74aba90d7073195ad1c67886c4570e5341/src/app.ts#L79) and [C#](https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp/blob/32c39268d60078ef54f21fb3c6f42d122b97da22/template-bot-master-csharp/Global.asax.cs#L17).

BTW the BotState API you're using above is deprecated, and may be turned off at some point, so I recommend explicitly setting your bot storage.

**Comment by register9091** [comment]
@aosolis yeah the bot state API does not seem to work. We want that the conversation the user is having with the bot is say stored only for the current session and when the user comes to chat with the bot the next time, he/she should have a clean slate to start with. We need it for our testers as its quite difficult for them to keep track of new elements with the previous messages and cards being already shown on the screen. So can we get some URL flag which can help in this scenario ?

**Comment by aosolis** [comment]
Unfortunately what you're asking for is not supported. Right now there is no way to delete a conversation. The thread will always be there: there's no way to delete it or clear the messages inside it. Attempting to start a new conversation between the bot and a user will return the same conversation.

The closest you can probably get is to clear your bot's memory of the conversation by deleting all state associated with that conversation id in your bot's state store. In your testing environment you could implement a command like `reset`, that would delete all your state and send a banner message to the thread that says something like `----conversation reset here----`, to hopefully make it clearer to your testers where the "new" conversation began.

**Comment by register9091** [comment]
Ok. Thanks 👍
