### ISSUE TITLE
Erroneous Reference to Microsoft.Bot.Connector 3.5.9?

### ISSUE THREAD

**Issue by corygehr** [OfficeDev/BotBuilder-MicrosoftTeams#133]
The package on Nuget references Microsoft.Bot.Connector 3.5.9, which is a version that is not available via Nuget.

This causes errors with Azure Function Apps as it always looks for the dependencies as requested by the package. I am getting FileNotFound exceptions because it cannot find that version.

Normally I would mitigate by using the Preview Packages for Microsoft.Bot.Connector but then this package doesn't use the new Namespace references for things like the 'Activity' class.

**Comment by corygehr** [comment]
Doh! Sorry, I'm misreading the versioning, thinking it's more like 3.1.5.2 and not 3.5.9.0.

Still, seeing lots of issues with this on an Azure Function and I can't figure out why. One moment it works, the next it doesn't due to the dependencies.

**Comment by tsahi** [comment]
Microsoft.Bot.Builder 3.5.9 is ancient. When I started my bot, it was already at 3.12.2.4. Am I expected to downgrade to this version?

Is this a real limitation? Would your code break if you reference a later version? On Functions there is no binding redirect, mind you.
