### ISSUE TITLE
Deep link broken on Android

### ISSUE THREAD

**Issue by timroesner** [OfficeDev/BotBuilder-MicrosoftTeams#136]
We have a bot running and are linking to it from our website to add it to Teams. This is working great on Desktop and iOS, but on Android Teams only flashes briefly, before redirecting back to Chrome. 

We used a deep link of the format as [shown in the Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test#adding-a-bot-for-personal-chat-only) in step 3

Test environment:
Android 7.0
Teams 2018.22.01.1
Chrome & Firefox

**Comment by arun-msft** [comment]
We have checked with engineering team, they confirmed it is a known issue and they are working as feature item for this
