### ISSUE TITLE
Creating chat between two members and the bot.

### ISSUE THREAD

**Issue by penkin** [OfficeDev/BotBuilder-MicrosoftTeams#138]
Is it at all possible to create a chat between two members of a channel and the bot itself? I'm trying to build a bot that will initiate a conversation between two people in a channel privately.

Thanks.

**Comment by arun-msft** [comment]
Currently we don't have these capabilities to create group chat, but these capabilities will be available as part of Q3/Q4 roadmap.

**Comment by qiu999** [comment]
Hi @arun-msft  , i also have the same demand about this, is there  available now ?

**Comment by Wajeed-msft** [comment]
@penkin , @qiu999  - Please have a look at [Adding bots to chats](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#adding-bots-to-chats).
