### ISSUE TITLE
Ability to @ mentions Bot is not working

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#147]
Bots in single user conversations do not require an @ mention - the user can just type the command. But Bots in channel conversations require the user to @ mention the bot to invoke it in a channel.

Documents ref:-
[get-started-app-studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio)
[apps-upload](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload)

I followed above documents and created a teams app with bot but, I'm not able to do @ mentions {botName} in channel. They only interaction I can get from teams to bot services is when its first time added to the channel and when I configure a bot and click setUp button to configure it for channel.

Things I tried so far:
1) created a manifest.json with same app ID and bot ID
2) created a manifest.json with different app ID and bot ID. where app ID was generated using App studio and, Bot Id was existing BOT id.
3) Used bothandle from bot portal as app name 
4) Used different name for App than bothandle.

None of the above fixed the issue. 

It worked when app was side loaded for 1st time teams channel.
![image](https://user-images.githubusercontent.com/32375467/46158000-91876600-c242-11e8-93f9-1ee5a941f34f.png)

I tried @ mention with name GinaApp but it didn't find. Where is GinaApp is Display name from [https://dev.botframework.com](https://dev.botframework.com)
![image](https://user-images.githubusercontent.com/32375467/46158052-aebc3480-c242-11e8-8e32-c259e9876c17.png)

I tried @ mention with name rjapp where rjapp was taken from **manifest.name** property.
![image](https://user-images.githubusercontent.com/32375467/46158078-be3b7d80-c242-11e8-8a16-369d81d95603.png)

**Comment by billbliss** [comment]
There's an anomaly in the way bot names are handled for sideloaded apps. The @mention comes from the name registered in Bot Framework. The manifest.name overrides this only when it's published in the AppSource store or when it's uploaded to the tenant app catalog.

What is the name of the bot as registered in Bot Framework? You should be able to mention @ginaapp.

**Comment by billbliss** [comment]
Fixed that too, will get picked up the next time we published. Thanks!

**Comment by rjgmail88** [comment]
@billbliss thank you for quick input on this issue. I appreciate :)
Before seeing your comments I got it working by unselecting following option which I marked in red.
Do you think that was blocking @ mention feature 

![image](https://user-images.githubusercontent.com/32375467/46167083-7a547280-c25a-11e8-9595-3e9b27a9a1c1.png)

Also, currently I am only able to @ mention BotNames from https://dev.botframework.com/bots
so looks like **manifest.name** is not overriding it.

**Comment by billbliss** [comment]
Yes, checking that would do it. That checkmark says your bot can't reply to messages from users. The scope wouldn't matter.
