### ISSUE TITLE
Hover text not available on wrapped text

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#151]
Hi @aosolis ,

Is there any way we can get hovering full text when a sentence is wrapped in a card?
[Example screenshot](https://imgur.com/nc3ZbqM)

As you can see in the above image, the wrapped text does not get a hovering text.
The result being in case of a wrap there is no way for an end user to figure out the full sentence.

Kindly provide a solution to enable text hover (at least in chrome) or take this as a feature request.

Thank you :)

**Card data**
{"type":"message","text":"","attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","content":{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.0","type":"AdaptiveCard","actions":[{"type":"Action.ShowCard","title":"Show Details","card":{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.0","type":"AdaptiveCard","body":[{"facts":[{"type":"Fact","title":"Main Category","value":"Computer Systems"},{"type":"Fact","title":"Supplier Name","value":"Random"},{"type":"Fact","title":"E-Mail Address","value":"supplier-do.not.reply@random.com"}],"type":"FactSet"},{"size":"large","spacing":"medium","text":"Test table","type":"TextBlock","weight":"bolder","wrap":true},{"columns":[{"items":[{"text":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","type":"TextBlock","wrap":false,"separator":true},{"text":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).","type":"TextBlock","wrap":false,"separator":true}],"type":"Column"},{"items":[{"text":"B","type":"TextBlock","wrap":false,"separator":true},{"text":"D","type":"TextBlock","wrap":false,"separator":true}],"type":"Column","separator":true}],"type":"ColumnSet","separator":false}]}}],"body":[{"items":[{"columns":[{"items":[{"horizontalAlignment":"center","size":"medium","type":"Image","url":"https://google.com"}],"width":"auto","type":"Column"},{"items":[{"size":"large","text":"Notebook Basic 15","type":"TextBlock","weight":"bolder","wrap":true},{"subtle":true,"isSubtle":true,"spacing":"none","text":"HT-1000","type":"TextBlock","wrap":true}],"width":"stretch","type":"Column"}],"type":"ColumnSet","separator":false}],"type":"Container"}]}}]}

**Comment by Wajeed-msft** [comment]
@register9091 - You can set **_"wrap": true_** for the textblocks so that it shows complete text. I could see it's explicitly set to false. 

Regarding showing a tooltip for truncated text, It would be a feature request.
