### ISSUE TITLE
Adaptive card with button type "Action.Submit" shows "Submitted" text on click

### ISSUE THREAD

**Issue by shalini12kohli** [OfficeDev/BotBuilder-MicrosoftTeams#154]
In adaptive card with buttons of action type "Action.Submit", when we click on it, "submitted" text appears at the bottom of the card which remains for a couple of minutes and disappears. is this standard behavior or can we configure it to stop showing this text.

**Comment by billbliss** [comment]
This is by design, but we will look into it.
