### ISSUE TITLE
Add support for .NetStandard

### ISSUE THREAD

**Issue by pavel-spacil** [OfficeDev/BotBuilder-MicrosoftTeams#156]
Hello, we have project using .net standard (2.1 actually) and we want to integrate MS Teams bot there. Other bot packages (like MS.Bot.Connector and MS.Bot.Connector.AspNetCore) are ready but this one has the sections about .net standard commented. Can you please add .net standard as supported target back? Thanks

**Comment by RamjotSingh** [comment]
We are working on the next major version which will support for NetStandard2.0.

P.S. .NetStandard 2.1 is not out yet. [Official documentation](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

**Comment by billbliss** [comment]
We do not. Hopefully soon.
