### ISSUE TITLE
Tab Removal only by admin

### ISSUE THREAD

**Issue by Talhakh** [OfficeDev/BotBuilder-MicrosoftTeams#158]
Can we disable removing the tab based on user context. i.e. Only allow admins to remove the tab not the user. I tried doing it based on the context but it enables the remove button after 5 seconds on its own.

**Comment by Wajeed-msft** [comment]
What do you mean by admin user here? 
If you mean team owners then it is available as part of team setting:
![image](https://user-images.githubusercontent.com/31851992/47566339-12707500-d949-11e8-85c6-e5f513063edf.png)
