### ISSUE TITLE
Basic authentication not working in TaskModule for Android

### ISSUE THREAD

**Issue by register9091** [OfficeDev/BotBuilder-MicrosoftTeams#161]
Hi,

I created a simple website which is protected using basic authentication. Now when i try to open it in a task module using the fallback URL on an Android device, i do not get a popup for Basic authentication. (I do get a popup when i load it in a task module in the browser or the desktop app)

Kindly look into this issue.

PS: You can try out a simple basic authentication web page from here
https://jigsaw.w3.org/HTTP/Basic/
User/Pass: guest/guest

**Comment by arun-msft** [comment]
@register9091 : Task module will not support mobile device yet. for now it will work desktop app and browser.

**Comment by billbliss** [comment]
It's under active development.

**Comment by register9091** [comment]
@billbliss: I do understand you have not gone GA with this. I was just bringing this to your notice that in case of fallback URL basic auth does not work on the app browser being opened up. If the same link were to be opened in chrome we do get a popup. 

I will also verify if SSO login has an issue, and update this issue accordingly. 

@arun-msft: I was referring to the fallback URL of task modules. Which does open up the task module on a mobile device.

**Comment by cagdasdavulcu** [comment]
> It's under active development.

i have a behavioral report for this topic.

@billbliss i tested your sample: 
https://github.com/OfficeDev/microsoft-teams-sample-task-module-nodejs

The links are being showed in mobile app, but these are not clickable. Buttons are clickable, but they are not working.

Do you have any feedback, when "Task Module" feature will be supported on Teams Mobile App?

**Comment by billbliss** [comment]
We don't have a date to share but it will be soon. I'm sorry I can't be more specific.
