### ISSUE TITLE
Teams Calling API don't respond with 202 Accepted

### ISSUE THREAD

**Issue by mwerghemmi** [OfficeDev/BotBuilder-MicrosoftTeams#165]
Hello,  
As per the documentation here  
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/call_answer

I should receive a 202 Accepted after i answer a call.. 

In my case i am receiving notification with status   "state": "Established" but never receive the 202 .. 
is it a known issue in the Platform ? 
Note: I am using Nodejs servicehostedmedia

Mefteh.

**Comment by kanchm** [comment]
Please provide the time and payload (with any personally identifiable data scrubbed) so we can track this on the server.  I recommend that you post this in the Calling github samples where we are monitoring all related questions.
https://github.com/microsoftgraph/microsoft-graph-comms-samples
