### ISSUE TITLE
Teams Calling:Cannot play prompt 

### ISSUE THREAD

**Issue by mwerghemmi** [OfficeDev/BotBuilder-MicrosoftTeams#166]
Hello,  
Trying to play a prompt after answering a call (call established). 
The API Call is not retrurning any answer no error... 

I am using the Graph Javascript SDK for the API calls. 

function PromptCall(CallId) {

    var Prompt =
    {
        "prompts": [
            {
                "@odata.type": "#microsoft.graph.mediaPrompt",
                "mediaInfo": {
                    "uri": "https://myaudio.blob.core.windows.net/prompts/couchplayin.wav",
                    "resourceid": "1D6DE2D4-CD51-4309-8DAA-70768651088E",
                },
                "loop": 5
            }
        ]
    }

    client
        .api("https://graph.microsoft.com/beta/app/calls/" + CallId + "/playPrompt")
        .post(Prompt, (err, res) => {
            console.log(JSON.stringify(" err  (prompt)  " + JSON.stringify(err, null, 1), null, 1));
            console.log(JSON.stringify("res    (prompt) " + JSON.stringify(res, null, 1), null, 1));
        });
}

Note: I am using Nodejs servicehostedmedia

**Comment by kanchm** [comment]
Please provide the `CallId` for the call and the time (in UTC) when the call was placed.  Also recommend moving this issue to github for calling SDK.
https://github.com/microsoftgraph/microsoft-graph-comms-samples
