### ISSUE TITLE
Advanced user interaction in prompts

### ISSUE THREAD

**Issue by cagdasdavulcu** [OfficeDev/BotBuilder-MicrosoftTeams#167]
Hello everyone,

is there any possibility to return a custom react application as prompt from a bot (it doesn't have to be a react application)? In my case, the bot should return an application, where user can mark one or more objects from an image and send it as a message to my bot without using static tabs for bots.

Thanks and regards,
Cagdas

**Comment by Wajeed-msft** [comment]
@cagdasdavulcu - Please have a look at [Task Module](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview). Let us know if that helps.

**Comment by cagdasdavulcu** [comment]
@Wajeed-msft  thank you! You can close this issue.
