### ISSUE TITLE
Reading posted image content and name

### ISSUE THREAD

**Issue by cagdasdavulcu** [OfficeDev/BotBuilder-MicrosoftTeams#170]
I'm working on a scenario, where user makes a photo and edits it to mark objects on image and posts it in a channel as a message. I thought, that this image will be automatically uploaded into sharepoint folder. But it will saved in a skype location like:
_https://eu-api.asm.skype.com/v1/objects/xxx/views/imgo_

This item type will be used:
_itemtype="http://schema.skype.com/AMSImage"_

I cannot read the content of any image because the api is not documented and i cannot extract the name of the image, because it uses object ids. 

I have the following questions:
- Do you have any Feedback, if teams will support this scenario?
- Is there any possibility to read image content and other information about image?

thank you!

**Comment by Wajeed-msft** [comment]
@cagdasdavulcu - We are working on adding support to read images which are pasted inline in chat messages.

Currently, only the images uploaded using upload option are stored in SharePoint.
![image](https://user-images.githubusercontent.com/31851992/49371273-ebae1700-f71c-11e8-94a5-d86ac4ba6ffc.png)


Alternatively, if your bot is @mention while sending these photos, then you can read those as an attachment in your bot code. Please have a look at [Receiving Attachments](https://github.com/Microsoft/BotBuilder-Samples/blob/v3-sdk-samples/CSharp/core-ReceiveAttachment/ReceiveAttachmentDialog.cs).

**Comment by cagdasdavulcu** [comment]
Is there any update for this topic?

**Comment by Wajeed-msft** [comment]
This is available now. Please try and let us know if you are facing any issues.
