### ISSUE TITLE
Click action for links with open url action not working

### ISSUE THREAD

**Issue by shreyasdn** [OfficeDev/BotBuilder-MicrosoftTeams#176]
hi,
     In an adaptive card the link with an open url action does not trigger any action and we get an console error shown below only in firefox but works in chrome and the client. 
![microsoftteams-image](https://user-images.githubusercontent.com/6490281/50946851-6e1abb00-14c1-11e9-8d31-f4ce614e34e6.png)

**Comment by arun-msft** [comment]
We have tried and openuri action working fine without any issues in firefox as well. Could you please share the adaptive card json?

**Comment by shreyasdn** [comment]
{
  "type": "message",
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.0",
        "type": "AdaptiveCard",
        "body": [
          {
            "columns": [
              {
                "items": [
                  {
                    "spacing": "none",
                    "text": "Here's what I have for catalog items.",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "style": "default",
                "type": "Column"
              }
            ],
            "type": "ColumnSet",
            "separator": false
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.0",
        "type": "AdaptiveCard",
        "actions": [
          {
            "type": "Action.OpenUrl",
            "title": "See more",
            "url": "valid url"
          }
        ],
        "body": [
          {
            "columns": [
              {
                "items": [
                  {
                    "size": "extraLarge",
                    "text": "Catalog Item List (3 of 14)",
                    "type": "TextBlock",
                    "weight": "bolder",
                    "wrap": false
                  }
                ],
                "style": "default",
                "type": "Column"
              }
            ],
            "type": "ColumnSet",
            "separator": true
          },
          {
            "columns": [
              {
                "items": [
                  {
                    "horizontalAlignment": "center",
                    "size": "medium",
                    "style": "default",
                    "type": "Image",
                    "url": "valid image url"
                  }
                ],
                "style": "default",
                "width": "auto",
                "type": "Column"
              },
              {
                "items": [
                  {
                    "size": "large",
                    "spacing": "none",
                    "text": "Logitech headset",
                    "type": "TextBlock",
                    "weight": "bolder",
                    "wrap": true
                  },
                  {
                    "spacing": "none",
                    "text": "37.00 EUR",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "style": "default",
                "type": "Column"
              }
            ],
            "type": "ColumnSet",
            "separator": true
          },
          {
            "columns": [
              {
                "items": [
                  {
                    "color": "accent",
                    "text": "Details",
                    "type": "TextBlock",
                    "wrap": false
                  }
                ],
                "selectAction": {
                  "type": "Action.OpenUrl",
                  "title": "Details",
                  "url": "valid url"
                },
                "style": "default",
                "width": "auto",
                "type": "Column"
              }
            ],
            "type": "ColumnSet",
            "separator": false
          }
        ]
      }
    }
  ]
}

**Comment by shreyasdn** [comment]
hi @arun-msft Please find above the json. This works in chrome and client but not on teams. Our environment is a test environment meaning our code works on the developer license teams account.

**Comment by arun-msft** [comment]
We were able to repro this on Mozilla. We have raised bug for that. Thanks for reporting.

**Comment by WorkspaceChetan** [comment]
> We were able to repro this on Mozilla. We have raised bug for that. Thanks for reporting.
One more issue.
When we use "onExecuteAction" then we cant open url in new tab.
