### ISSUE TITLE
[Question] Is it possible to open url inside of teams desktop app

### ISSUE THREAD

**Issue by 01** [OfficeDev/BotBuilder-MicrosoftTeams#184]
I would prefer to have a url open within teams desktop app as opposed to launching into the a seperate web browser. I have seen that the signin card is the only scenario where that seems to happen. How would I recreate the same result as the signin card?

**Comment by Gousia-MSFT** [comment]
@01 You can open  a url in the form of a popup within teams desktop app using [Task Module](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview).

**Comment by 01** [comment]
The task module is a a fixed tab, it can not be minimized or move out of the way. Its what we are currently utilizing for serving html content that we dont want in a dedicated tab. That said I am mistaken it seems about the sign in card behavior.

**Comment by 01** [comment]
@Gousia-MSFT
