### ISSUE TITLE
Missing 'name' property from the interface ChannelAccount in Node.js SDK

### ISSUE THREAD

**Issue by yauscher** [OfficeDev/BotBuilder-MicrosoftTeams#187]
when I call connector.fetchMembers() I get a list containing users info where all of them have the property 'name', but I get a typing error when trying to use this property because it's missing from the interface of ChannelAccount. 
I've checked the C# SDK and it is present there: 
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/TeamsAPI/Models/TeamsChannelAccount.cs

**Comment by RamjotSingh** [comment]
You have to cast the ChannelAccount into an TeamsChannelAccount using AsTeamsChannelAccount extension method (refer to https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/ConversationExtensions.cs)

**Comment by RamjotSingh** [comment]
@robin-liao For NodeJS

**Comment by code0007** [comment]
I got a similar issue
