### ISSUE TITLE
onSelectItem compose extension 

### ISSUE THREAD

**Issue by 01** [OfficeDev/BotBuilder-MicrosoftTeams#189]
Is there any way to have onSelectItem allow for a task module to be opened instead of a card being put into the message box?

**Comment by Wajeed-msft** [comment]
Currently this is not supported. Could you please elaborate your scenario here? May be you could use [Action type message extensions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/create-extensions#action-type-message-extensions).

**Comment by 01** [comment]
My scenario is a search functionality but not for the purpose of sending a result as a card in a message to another user. Would like  for user to do be able to do search and on selecting one of the cards from the result list invoke a task module. For now a not ideal work around is to return an empty invokeResponse and have the bot send a card with the some of the information with a invoke button for the task module.

**Comment by Wajeed-msft** [comment]
Currently, you cannot open Task Module when user selects an item from the search result. 

Could you please try Praise messaging extension and let us know if you are looking something similar?
![image](https://user-images.githubusercontent.com/31851992/56880727-836d2280-6a7b-11e9-8062-b622a27de876.png)

**Comment by 01** [comment]
@Wajeed-msft thank you for your response. I am familiar and am utilizing message extensions actions with preview functionality. I was hoping to accomplish the same functionality from a onSelectItem from messagingquery. 

Do a search, get a list, select one and preview it before sending it or simply view it as well. (Like the wikipedia extension except  user would be able to read a extended summary or even view the entire page in a module before deciding to send it).
