### ISSUE TITLE
Adaptive Card with Action.Submit not working

### ISSUE THREAD

**Issue by wilmabrinkmeyer** [OfficeDev/BotBuilder-MicrosoftTeams#191]
I have a simple Adaptive card in my v4 Bot with two buttons. But in Teams (neither desktop nor web) I do not get any response, in Webchat it works fine.
Here the json.
{ "type": "AdaptiveCard",
  "backgroundImage": "https://mcdn.wallpapersafari.com/medium/21/61/zkNgu4.jpg",
  "body": [
    {
      "type": "TextBlock",
      "size": "Large",
      "weight": "Bolder",
      "color": "Accent",
      "text": "Upload Document?"
    },
    {
      "type": "TextBlock",
      "size": "Small",
      "weight": "Bolder",
      "text": "If you upload your requirements form I can analyse it and help you to fill out the blanks",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Upload Document",
      "color": "Black",
      "data": "Upload"
    },
    {
      "type": "Action.Submit",
      "color":"Black",
      "title": "No thanks",
      "data": "No"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}

**Comment by Wajeed-msft** [comment]
With above JSON, you should be getting call-back in your bot code. However, you won't be getting actual data values as **data** needs to be JSON object and not plain string. 

Here is how you can get your text displayed in chat windows for Microsoft Teams and get data in payload when user click on action:

```
"actions": [
    {
      "type": "Action.Submit",
      "title": "Upload Document",
      "data": {
        "msteams": {
          "type": "imBack",
          "value": "Upload"
        }
      }
    },
    {
      "type": "Action.Submit",
      "title": "No thanks",
      "data": {
        "msteams": {
          "type": "imBack",
          "value": "No"
        }
      }
    }
  ]
```
Please have a look at [Adaptive Card actions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#adaptive-card-actions) documentation for more details. Please let us know if you are facing any issues.
