### ISSUE TITLE
How to disable button response on second click in Microsoft teams?

### ISSUE THREAD

**Issue by vishmonne** [OfficeDev/BotBuilder-MicrosoftTeams#192]
Hi Team,

I wanted to know is there any way in teams where we can disable the second button click on a button. I don't want the user to scroll back and click on the button again if they have already clicked it once before.

I have read a article on Suggested actions :
[https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-suggested-actions?view=azure-bot-service-3.0](url)

This one works in bot emulator but not in teams.

So what to know if there is any solution to my problem in Microsoft teams

**Comment by Gousia-MSFT** [comment]
@vishmonne- [Suggested actions](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions#openurl) are not supported in Microsoft Teams. Here is how you could achieve this with [Card Updates](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#updating-messages):
1. Create the card:

```
                var Card = new AdaptiveCard(new AdaptiveSchemaVersion("1.0"))
                {
                    Body = new List<AdaptiveElement>()
                    {
                        new AdaptiveTextBlock(){Text="This is a test adaptive card"}
                    },
                    Actions = new List<AdaptiveAction>()
                    {
                        new AdaptiveSubmitAction()
                        {
                           Title="Update Me",
                        }
                    }
                };
                var attachment = new Attachment()
                {
                    ContentType = AdaptiveCard.ContentType,
                    Content = Card
                };
                reply.Attachments.Add(attachment);
                await `connector.Conversations.ReplyToActivityWithRetriesAsync(reply);
```

2. Here is the code to update your card on click of a button:
```
                var reply = Activity.CreateMessageActivity();
                var Card = new AdaptiveCard(new AdaptiveSchemaVersion("1.0"))
                {
                    Body = new List<AdaptiveElement>()
                    {
                       new AdaptiveTextBlock(){Text="This is a test adaptive card without button"}
                    },
                };
                var attach = new Attachment()
                {
                    ContentType = AdaptiveCard.ContentType,
                    Content = Card
                };
                reply.Attachments.Add(attach);
                await connector.Conversations.UpdateActivityAsync(activity.Conversation.Id, activity.ReplyToId, (Activity)reply);
```

**Comment by rjgmail88** [comment]
@vishmonne ,  are you referring to [Update](https://github.com/microsoft/botframework-sdk/blob/3.0/Node/core/src/bots/ChatConnector.ts#L358) method. 

I also wanted to know how your solution will fit into following user case where Bot's skill flow is as  follows. 

( At 4pm )  
User: Tell me available times to meet Bob for today
Bot: Shows Adaptive cards with 4 submit button which are nothing but available times 
User: Clicks on one if the submit 
bot: Shows some plain text output and drops the invite on Bob's and User's calendar.

( At 5pm )
User just goes to old conversation and click on existing suggested submit where data available data is stale. 

are you suggesting to have 'Update' button on the Adaptive card in case User wanted new available times for Bob ?
