### ISSUE TITLE
Adaptive Cards Limited Width

### ISSUE THREAD

**Issue by 01** [OfficeDev/BotBuilder-MicrosoftTeams#193]
It seems that Adaptive cards have a forced width sides while text activities and o365ConnectorCards dont. Is this by design? If not how can the width be increased?

**Comment by Gousia-MSFT** [comment]
@01  Adaptive card width is managed by Microsoft Teams channel so that it renders well on all the device includes mobile. Currently, there is no option to set the custom width to adaptive card.

**Comment by 01** [comment]
I dont mean setting a custom width. Simply that it take the max width of the chat like everything else does. If I send a text message or an o365connector card it takes the maximum width, adaptive cards take some width closer to 60-70%
