### ISSUE TITLE
Adaptive card with Action.Submit button is not working in IOS Mobile Teams APP 

### ISSUE THREAD

**Issue by vishmonne** [OfficeDev/BotBuilder-MicrosoftTeams#194]
Hi All,

I am not able to click any of the buttons on the card while i am using through my teams app in IOS phone, whereas i am able to click on the buttons through my android phone as well as the desktop teams app. Any suggestions or solutions on this issue would be really helpful.

C# SDK 3
Adaptive card version -1.0

**Comment by Aditya0603** [comment]
@vishmonne can you please provide a sample join of the card you are using.

**Comment by Wajeed-msft** [comment]
Please re-open with sample json for your card.
