### ISSUE TITLE
Adaptive Card Input.Date fields only work correctly in English

### ISSUE THREAD

**Issue by v-kydela** [OfficeDev/BotBuilder-MicrosoftTeams#195]
**While this is related to bots because it involves Adaptive Cards, this is a Teams client issue and not an issue with the SDK. Since this is a critical blocker for all customers who want Input.Date fields to work for non-English end users, I want to escalate this as much as possible. If there is a better place to report Teams client bugs internally, please let me know.**

## Description

A [customer](https://github.com/microsoft/botframework-sdk/issues/5411) reported that their Adaptive Card Input.Date fields were not showing up in the data that gets sent to the bot in response to a submit action. We eventually determined that the problem was occurring because his Teams client was configured to use French. I then did some experimenting and found out that it works sometimes depending on the month of the selected date, and that the months that work are not consistent across languages. Here are some screenshots of an Adaptive Card with 12 Input.Date fields along with the values that get returned in a few different languages:

### Adaptive Card

```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "Input.Date",
      "id": "id-date1",
      "value": "01/02/03"
    },
    {
      "type": "Input.Date",
      "id": "id-date2",
      "value": "02/03/04"
    },
    {
      "type": "Input.Date",
      "id": "id-date3",
      "value": "03/04/05"
    },
    {
      "type": "Input.Date",
      "id": "id-date4",
      "value": "04/05/06"
    },
    {
      "type": "Input.Date",
      "id": "id-date5",
      "value": "05/06/07"
    },
    {
      "type": "Input.Date",
      "id": "id-date6",
      "value": "06/07/08"
    },
    {
      "type": "Input.Date",
      "id": "id-date7",
      "value": "07/08/09"
    },
    {
      "type": "Input.Date",
      "id": "id-date8",
      "value": "08/09/10"
    },
    {
      "type": "Input.Date",
      "id": "id-date9",
      "value": "09/10/11"
    },
    {
      "type": "Input.Date",
      "id": "id-date10",
      "value": "10/11/12"
    },
    {
      "type": "Input.Date",
      "id": "id-date11",
      "value": "11/12/13"
    },
    {
      "type": "Input.Date",
      "id": "id-date12",
      "value": "12/13/14"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

### French (France)

![image](https://user-images.githubusercontent.com/41968495/59390384-eeba3d80-8d25-11e9-83f6-9c54a287ff31.png)

```json
{"id-date1":"2003-01-02","id-date3":"2005-03-04","id-date9":"2011-09-10","id-date10":"2012-10-11","id-date11":"2013-11-12"}
```

### Italian (Italy)

![image](https://user-images.githubusercontent.com/41968495/59391023-e236e480-8d27-11e9-8cb6-6ee5c2d4e17e.png)

```json
{"id-date2":"2004-02-03","id-date3":"2005-03-04","id-date4":"2006-04-05","id-date11":"2013-11-12"}
```

### Dutch (Netherlands)

![image](https://user-images.githubusercontent.com/41968495/59390830-43aa8380-8d27-11e9-997f-3811274f8ae9.png)

```json
{"id-date1":"2003-01-02","id-date2":"2004-02-03","id-date4":"2006-04-05","id-date6":"2008-06-07","id-date7":"2009-07-08","id-date8":"2010-08-09","id-date9":"2011-09-10","id-date11":"2013-11-12","id-date12":"2014-12-13"}
```

By observing these results, I was able to deduce the pattern. The only values that are returned are the values with months that are abbreviated the same way in English. For example, in Italian only the dates in February, March, April, and November are returned because those are abbreviated to Feb, Mar, Apr, and Nov in both English and Italian.

**This tells us what must be causing the bug. The configured locale is only used for displaying the Input.Date fields and not for interpreting them. So when the Adaptive Card's submit action is clicked, Teams tries to read the value of each Input.Date as though they're all in English, and then only puts the values that could be parsed as English in the result.**

Also note that in some languages like Spanish, Portuguese, and German, months are only displayed as numbers and not abbreviations:

![image](https://user-images.githubusercontent.com/41968495/59390645-c67f0e80-8d26-11e9-914e-38efc7feabda.png)

```json
{"id-date1":"2003-02-01","id-date2":"2004-03-02","id-date3":"2005-04-03","id-date4":"2006-05-04","id-date5":"2007-06-05","id-date6":"2008-07-06","id-date7":"2009-08-07","id-date8":"2010-09-08","id-date9":"2011-10-09","id-date10":"2012-11-10","id-date11":"2013-12-11"}
```

However, the issue still persists even in this case. Notice that each date is misrepresented in the result, with the month value and day value switched. This is because months are interpreted in English as MM-DD-YYYY but are displayed in those other languages as DD-MM-YYYY. As a result, most date values will be returned incorrectly and dates with a day value greater than 12 won't get returned at all.

## Repro Steps

1. Configure Teams to use a non-English locale
2. Connect to a bot that sends an Adaptive Card to the user with an Input.Date field and a submit action
3. Click the submit button and observe the incorrect results returned to the bot
    - If the months are abbreviated, the Input.Date result will not be present if the month is abbreviated in a way that isn't the same as English
    - If the dates are displayed in DD-MM-YYYY format, the result will have the month value and day value switched

## Expected Behavior

When interpreting Input.Date fields in Adaptive Cards, Teams should use a recognizer that's paired up with or at least consistent with the locale-specific date renderer. Language translation needs to go both ways. Input should match output.

Better yet, Teams shouldn't even try to interpret the displayed date string at all. It should just use an internally-stored date value and apply that to the submit action's data directly.

## Additional Context

I have observed this bug in both the Windows desktop client and teams.microsoft.com.

Also, it makes no difference how you format the date in the Adaptive Card itself. That date is just a default value, and the user-selected value is what's relevant for the bug.

**Comment by Gousia-MSFT** [comment]
@v-kydela Thanks for reporting this. We have raised a bug for it.

**Comment by v-kydela** [comment]
@Gousia-MSFT - Did you close this because it's been fixed?

**Comment by Gousia-MSFT** [comment]
We have a bug on this and we are tracking this internally.
