### ISSUE TITLE
Mention entity text is not valid. 

### ISSUE THREAD

**Issue by SimSpfx** [OfficeDev/BotBuilder-MicrosoftTeams#199]
**Describe the bug**
Adding a mentions to message entities is not working.
I get the the next error : Mention entity text is not valid.

**SDK Version**
Latest beta
.Net Version
Core 2.x
Expected behavior
Add a mention

```
 var connectorClient = new ConnectorClient(new Uri(stepContext.Context.Activity.ServiceUrl), identity);
                var teamId = stepContext.Context.Activity.GetChannelData<TeamsChannelData>().Team.Id;
                var members = await connectorClient.Conversations.GetConversationMembersAsync(teamId);

                var mentions = new List<Entity>();
           
                var message = Activity.CreateMessageActivity();
                foreach (var member in members)
                {
                    mentions.Add(new Mention(new ChannelAccount(member.Id,member.Name,"",member.AadObjectId), "a notification message, for following users : ", ""));

                }
     
                message.Entities = mentions;
```

**Comment by Wajeed-msft** [comment]
Could you please `teamsContext.AddMentionToText()` to add mentions?


                    var message = Activity.CreateMessageActivity();
                    message.Text = "a notification message, for following users: ";
                    foreach (var member in members)
                    {
                        message = teamsContext.AddMentionToText(message, new ChannelAccount(member.Id, member.Name, "", member.AadObjectId), member.Name);

                    }
                    await turnContext.SendActivityAsync(message, cancellationToken);
```
