### ISSUE TITLE
Customer Service scenario with MS Teams.

### ISSUE THREAD

**Issue by hshahbaz** [OfficeDev/BotBuilder-MicrosoftTeams#200]
Hi All, 

I am working on a chatbot with LUIS and QnA Maker that works in a customer service scenario with MS Teams as the platform which the customer service is going to use. I am thinking of having the bot as a 1:1 chat in every customer service MS Teams.  Whenever a user wants to talk to a customer service agent by typing "i want to talk to a customer service agent" or similar, the user is transferred by bot to MS Teams. 

I want to know if having a 1:1 chat in every customer service agent teams is a good idea or should I create Teams and channels under it with every new conversation. This scenario seems limiting to me as bot might hit the channels limit and every conversation is open to everyone who is a part of that team. 

Plus, is scenario one plausible, where every agent has a chatbot in their team and the chatbot routes the conversation from user to agent(whoever is free)?

Thoughts and help in the right direction  please?

**Comment by Trinetra-MSFT** [comment]
Creating new channel for every user is not a feasible solution so the best way to have 1:1 conversation with bot and user than transfer it to the service agent who is free. Please have a look at documentation for [Personal (1:1) conversation with Bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-personal)
