### ISSUE TITLE
Is it possible to open the Settings in an Adaptive card instead of opening an external url?

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/BotBuilder-MicrosoftTeams#201]
Hi there,

I'm currently developing a Teams app. I watch the official sample code, which would open the Settings in an external site via a URL when right clicking the "Settings" of the message extension app bar.

Question: Could we change this to open a card in teams directly but not open the URL?

Thanks!

**Comment by Gousia-MSFT** [comment]
@RukaiYu Not sure which "Settings" you are talking about. Could you please share a screenshot for our understanding.

**Comment by RukaiYu** [comment]
![image](https://user-images.githubusercontent.com/3942409/63488191-a915b000-c4e0-11e9-8129-50f82b84941d.png)
Hi @Gousia-MSFT 
Indeed, I mean the settings like above (When right click on my message-extension app)

**Comment by Gousia-MSFT** [comment]
@RukaiYu Could you please elaborate on the scenario for which you would want to change the current behaviour?

**Comment by clearab** [comment]
@RukaiYu This is a pretty interesting idea, that unfortunately isn't currently possible. At the moment you need to create a configuration page, then handle the resulting event when the page is submitted. We'll investigate and consider adding to the backlog for the future.

**Comment by RukaiYu** [comment]
@Gousia-MSFT  @clearab 
OK.. Let me explain a bit clear what we want so far 

1. Currently if right click on the message extension app, open the Settings it can only open the configuration page URL in separated browser tab, right?
2. We think is it possible to at last open the configuration page within the Teams windows? Like this:
![image](https://user-images.githubusercontent.com/3942409/63578110-63c9af00-c5c2-11e9-8c2b-8f7f70f3a6ca.png)

I'm trying to use the TaskModule with deepLink, no getting result yet.

**Comment by Gousia-MSFT** [comment]
@RukaiYu As @clearab mentioned this isn't currently supported but is something that we could consider for future. Thanks for reaching out!
