### ISSUE TITLE
[Question]Is there any api that indicates the user is using mobile or desktop or web app of Teams?

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/BotBuilder-MicrosoftTeams#203]
Is there any api that indicates the user is using mobile or desktop or web app of Teams?

**Comment by Gousia-MSFT** [comment]
@RukaiYu Here is how you could get the platform information:
1. In Tabs, you could get it in the [Tab Context](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context).
2. In Bot, this information can be obtained in the activity payload itself. 
![image](https://user-images.githubusercontent.com/45553518/63678859-b3e88180-c80d-11e9-9015-b1eb6e55e909.png)

**Comment by RukaiYu** [comment]
@Gousia-MSFT Thanks a lot!
