### ISSUE TITLE
npm install botbuilder-teams --save fails bc package.json name is "botbuilder-teams"

### ISSUE THREAD

**Issue by Joel-fogue** [OfficeDev/BotBuilder-MicrosoftTeams#206]
Hi i'm totally new with all of this: 

The doc says to grab the npm package for the botbuilder-teams; howver if you ran this command:
`npm i botbuilder-teams --save`

You get the following error:

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "botbuilder-teams" under a package
npm ERR! also called "botbuilder-teams". Did you name your project the same
npm ERR! as the dependency you're installing?
```
I had to rename my package name in `package.json` to something else to successfully install this module:
so from this `"name": "botbuilder-teams"`, to this: `"name": "botbuilder-teams-testing"` and it worked

I can submit a quick PR if this a valid issue; I'm very new at this; I have spent 2 days on trying to successfully get my emulator to respond to "hello" after running "node app.js"

**Comment by Trinetra-MSFT** [comment]
Are you trying Microsoft Teams [Hello World Sample](https://github.com/OfficeDev/msteams-samples-hello-world-nodejs)?

**Comment by Gousia-MSFT** [comment]
@Joel-fogue Please re-open if you are still facing any issues.
