### ISSUE TITLE
How to show Setting entry in mobile client when displaying Adaptive Card

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/BotBuilder-MicrosoftTeams#208]
Hi Team,

I have a message extension Teams app, it will open a Adaptive Card, but it doesn't show the setting entry like the Github's.
![image](https://user-images.githubusercontent.com/3942409/64932331-c2f0ab80-d870-11e9-8374-3e107d3a5adc.png)
![image](https://user-images.githubusercontent.com/3942409/64932335-c71cc900-d870-11e9-8509-b43aec34a2aa.png)

As you can see the Github's card can have the Setting icon at the right top corner.

How to add that in my Card Response?

Thanks!
Regards,
Rukai

**Comment by Trinetra-MSFT** [comment]
Currently this isn't supported, At the moment you need to create a configuration page, then handle the resulting event when the page is submitted.  We would consider this for future.
