### ISSUE TITLE
[Question] Is it possible to get an event notification when the app is uninstalled?

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/BotBuilder-MicrosoftTeams#210]
Hi Team,
Is it possible to get an event notification when the app is uninstalled?

User Case:
1. When a user uninstalls the app, I want to do some cleanup work like, remove the authorization state of that user in our DB.

**Comment by Gousia-MSFT** [comment]
@RukaiYu When a Bot is added/removed, we get a [conversation update event](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications). You could handle Conversation Update and perform the actions you want.

**Comment by RukaiYu** [comment]
Thanks @Gousia-MSFT 
While I'm not looking for that notification only for Bot,
But for the uninstall for the message-extension at the messaging bar
![image](https://user-images.githubusercontent.com/3942409/65306787-d2e1f580-dbb8-11e9-99a9-bcd8b4c85d4b.png)

**Comment by clearab** [comment]
Hi - That's an interesting idea. We don't currently send install/uninstall events for messaging extensions, only for conversation bot installs. We'll add it to the backlog for consideration in a future iteration.
