### ISSUE TITLE
[Teams Bug] Icons and images can not render in Safari in Teams app

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/BotBuilder-MicrosoftTeams#211]
Hi Team,

Don't know where to raise this issue, but I just post it here:

We have an app with a message extension feature installed. In Chrome and Edge, the app icon and images(png file) can display correctly. While in Safari, the App Icon and images in the Adaptive Card can not be loaded, see below. The function is working fine, but the images are dark and not loaded.

Does anyone know the reason? Is it teams bug?

Thanks!

![image](https://user-images.githubusercontent.com/3942409/65493993-92e77f00-dee6-11e9-9212-9d99d754f382.png)
![image](https://user-images.githubusercontent.com/3942409/65494248-04bfc880-dee7-11e9-9925-2238f6f252b2.png)

**Comment by Gousia-MSFT** [comment]
@RukaiYu Were you able to repro this for any other app? Could you please share the manifest of the app where this could be reproed?

**Comment by RukaiYu** [comment]
@Gousia-MSFT Hello, would you mind to provide your email address? I can send you privately. Thanks.

**Comment by Gousia-MSFT** [comment]
Please send it out to the email alias mentioned in the [feedback page](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback).
