### ISSUE TITLE
How to send an HTML attachment from a Microsoft Teams bot

### ISSUE THREAD

**Issue by catchmeifyou** [OfficeDev/BotBuilder-MicrosoftTeams#212]
I noticed that when you use the app to send a card to another user, it has the desired effect- a short summary of the weather appears in the toast popup. Looking inside the JSON that represents that message shows that the "card" is actually an HTML attachment.

Am I able to replicate this by sending an HTML attachment? I have (naively) tried the following but it causes an exception:

```
  Activity reply = new Activity();
            reply.Type = ActivityTypes.Message;
            reply.Text = "Test the toast";

            reply.Conversation = new ConversationAccount()
            {
                Id = conversationResponse.Id
            };
            reply.Attachments.Add(new Attachment()
            {
                ContentType = "text/html",
                Content = "<div>Some generated html</div>"
            });
```

The exception I'm getting is "Operation returned an invalid status code 'BadRequest'" from within mscorlib.dll.

**Comment by Gousia-MSFT** [comment]
@catchmeifyou Sending a Html attachment from a bot is not currently supported. You could try opening the Html content inside a [Task Module](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview) .

**Comment by catchmeifyou** [comment]
Thank you for response.
