### ISSUE TITLE
Adaptive cards and builtin browser

### ISSUE THREAD

**Issue by saraswat40** [OfficeDev/BotBuilder-MicrosoftTeams#213]
Is it possible to open the builtin browser when using adaptive cards. The default actions (openUrl) opens the link in a browser. I have also tried something like this but it doesn't work either:
```
{
  "type": "Action.Submit",
  "title": "Click me for signin",
  "data": {
    "msteams": {
        "type": "signin",
        "value": "https://signin.com",
    }
  }
}
```

**Comment by Gousia-MSFT** [comment]
@saraswat40 Do you want to open a url inside Teams itself? Please try using [TaskModule ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-overview)and see if that helps. Please let us know if you need any help.

**Comment by saraswat40** [comment]
@Gousia-MSFT, thanks for responding. I didn't mean a modal dialog. See this documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-actions

At the top, for openUrl it talks about a default browser. This is not the default OS browser but a default teams browser. It only opens via an action from either the Hero or the thumbnail card. If you add a similar action to an adaptive card, the action opens the url in the default OS browser. I am trying to find out if there is a way to open the default teams browser.

**Comment by Gousia-MSFT** [comment]
@saraswat40 Could you please help me understand what do you mean by default teams browser?? Please share a screenshot of where you are expecting the url to open.

**Comment by saraswat40** [comment]
See below. Notice the teams logo on the top left of the browser window.

![image](https://user-images.githubusercontent.com/3200933/66130980-9f439a00-e5c0-11e9-8ff3-8c0c474c4c56.png)

**Comment by Gousia-MSFT** [comment]
@saraswat40 You need to specify the Action as SignIn Action for opening the url in this way. Also, please make sure that you specify these values in the validDomains section of your manifest.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries.
