### ISSUE TITLE
Capturing the bot message details on click of reactions (messageReactions) in teams.

### ISSUE THREAD

**Issue by arpitha-mm** [OfficeDev/BotBuilder-MicrosoftTeams#214]
I have to capture the details of bot message and the corresponding reaction details when the end user clicks on any kind of "reaction" on a message from bot in MS teams. 

![image](https://user-images.githubusercontent.com/53615496/66930160-d0f14200-f051-11e9-8d80-baf3d48e535c.png)

**Issue** : 
Right now I am unable to find the particular message details like text of bot response user reacted to/ time stamp/ any unique ID in order to store the reaction details and present it in report form for bot response.

**The turnContext.activity details are as below.**

{
    "reactionsAdded": [
        {
            "type": "like"
        }
    ],
    "type": "messageReaction",
    "timestamp": "2017-10-16T18:45:41.943Z",
    "id": "f:9f78d1f3",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/amer-client-ss.msg/",
    "from": {
        "id": "29:1I9Is_Sx0O-Iy2rQ7Xz1lcaPKlO9eqmBRTBuW6XzkFtcjqxTjPaCMij8BVMdBcL9L_RwWNJyAHFQb0TRzXgyQvA",
        "aadObjectId": "c33aafc4-646d-4543-9d4c-abd28e4d2110"
    },
    "conversation": {
        "isGroup": true,
        "conversationType": "channel",
        "id": "19:3629591d4b774aa08cb0887902eee7c1@thread.skype"
    },
    "recipient": {
        "id": "28:f5d48856-5b42-41a0-8c3a-c5f944b679b0",
        "name": "SongsuggesterLocal"
    },
    "channelData": {
        "channel": {
            "id": "19:3629591d4b774aa08cb0887902eee7c1@thread.skype"
        },
        "team": {
            "id": "19:efa9296d959346209fea44151c742e73@thread.skype"
        },
        "tenant": {
            "id": "72f988bf-86f1-41af-91ab-2d7cd011db47"
        }
    },
    "**replyToId**": "**1:19uJ8TZA1cZcms7-2HLOW3pWRF4nSWEoVnRqc0DPa_kY**"
}

**Question** : Can we use this **replyToID** to fetch any details using MS teams API? or is there any other way to fetch the details as mentioned above?

**Comment by Gousia-MSFT** [comment]
@arpitha-mm You could get the details of the message using [List channel message](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http) Graph API. Please try using this API using the messageId your bot receives in the payload.

**Comment by arpitha-mm** [comment]
@Gousia-MSFT Thanks for the response. Yes, I could get the details of all the message using List channel message. But I don't want the list of all message, I only need the details of particular message which user reacts for bot response in teams. 

I even tried following the Microsoft articles to get the above mentioned details and they're as below,
[https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#base-uri](url)
[https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#bot-to-connector](url)

But still unable to figure out how to identify the reacted message details like "Text, timestamp, unique ID etc,."

**Comment by Gousia-MSFT** [comment]
@arpitha-mm Please try passing the message id to the api call to fetch details of the particular message. Please have a look at [Get channel message](https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&tabs=http).

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any issues.
