### ISSUE TITLE
Dissapearing chat input window in bot privat chat

### ISSUE THREAD

**Issue by SimSpfx** [OfficeDev/BotBuilder-MicrosoftTeams#218]
Hello,

When you open a private chat with a bot in ms teams the chat window dissapears. Resulting in not being able to chat in anyway. This is what is dissapearing:
![image](https://user-images.githubusercontent.com/47321821/69797757-8cb89c00-11d0-11ea-8add-37849bd64adb.png)

I enabled private chat for my bot and it used to work in the past. But suddenly it stopped.

When i open ms teams in the browser it has display:none!important on the chat input box.
I know this might not be the best place for it. But i cannot find anything anywhere about this behaviour.

Kind regards
Simon

**Comment by Gousia-MSFT** [comment]
@SimSpfx Is your bot working in teams scope? Did you add your bot as a [notification-only-bot](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-notification-only)?

**Comment by SimSpfx** [comment]
@Gousia-MSFT it is a private and group chat bot. But it is very weird behavior. I have the issue but my colleague with the same bot does not. 

I tryed: 
clearing cache
readding bot
Redeploying

I will try now:
Ill uninstall and remove teams completely and than readd it and come back to you.

**Comment by Gousia-MSFT** [comment]
@SimSpfx Were you able to check the issue with your peers? Are you facing any issues?

**Comment by SimSpfx** [comment]
Nothing works. Tryed about everything. I noticed in the browser app that display none styling is applied. No idea why.

Kind regards
Simon

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Gousia-MSFT** [comment]
@SimSpfx Could you please share your app manifest with us?

**Comment by Gousia-MSFT** [comment]
Please re-open with the app manifest if you are still facing the issue.
