### ISSUE TITLE
Can't mention a user in channel

### ISSUE THREAD

**Issue by guyfreund** [OfficeDev/BotBuilder-MicrosoftTeams#222]
I'm using the json format for mentioning as discussed [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=json#nodejs-example-code-check-for-and-strip-bot-mention) and when I look into Teams UI I just see the user mentioned in purple but when moving the cursor on it there's no link to user. Is this a known bug?
This is the JSON I'm using:
```
{
    'type': 'message',
    'text': 'hi <at>Eran Korish</at>',
    'entities': [{'type': 'mention', 'mentioned': {'id': 'e2397ddc-d33f-4324-a6d4-5955ae199903', 'name': 'Eran Korish'},
                  'text': '<at>@Eran Korish</at>'}]
}
```
A mention through the bot API (doesn't show the user)
![image](https://user-images.githubusercontent.com/53565845/72090595-06d35900-3317-11ea-85b9-f5720a717eb3.png)

A mention through the UI
![image](https://user-images.githubusercontent.com/53565845/72090628-1bafec80-3317-11ea-8c63-10d615fbbabd.png)

**Comment by Gousia-MSFT** [comment]
@guyfreund Could you please try out this [code ](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#tabpanel_CeZOj-G++Q-1_dotnet)to @mention user?

**Comment by guyfreund** [comment]
@Gousia-MSFT That’s the one I’m using, but in JSOn format injected to the API call.

**Comment by Gousia-MSFT** [comment]
@guyfreund Are you trying this using Graph API or using a bot?

**Comment by guyfreund** [comment]
@Gousia-MSFT - Using the bot API.

**Comment by Gousia-MSFT** [comment]
@guyfreund Could you please try using the 29:XXX ID instead of the AAD Id of the user?

**Comment by guyfreund** [comment]
@Gousia-MSFT Sure, I’ll try it and comment here. BTW, when using api graph to fetch users, the “id” field of the user is it’s aad is or the regular one?

**Comment by Gousia-MSFT** [comment]
@guyfreund That is the AAD ID of the user.

**Comment by guyfreund** [comment]
@Gousia-MSFT - As can be seen in the [users documentation of graph api](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) the're only one id field that can be reterived. How am I supposed to get the relevant id in the mention context?
