### ISSUE TITLE
[MsTeams][Mobile][Bot] Mobile teams does not have support for attachments in bot 

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [OfficeDev/BotBuilder-MicrosoftTeams#236]
MS Teams App on mobile does not have support for attachments in bot. Can you help by when can we expect this feature ?

**Comment by Nikitha-MSFT** [comment]
Sending and receving files to bots on mobile is currently not supported. This is something we are working on but we do not have an ETA on when this will be available.
