### ISSUE TITLE
teams message reaction should send message id and type of reaction in activity

### ISSUE THREAD

**Issue by Harshul9089** [OfficeDev/BotBuilder-MicrosoftTeams#238]
Hi all ,

FYI
It's not an issue but i need a feature request from you all . please assist me.

**description:-**
As webchat is using activity middleware to send some extra parameters to map for which message user have reacted and conversation id with watermark which is helping me to get mapping of everything which is needed to log.

**i need the same feature  like the conversation id with message id, reaction type and message on which user reacted in Microsoft teams also.**

-- ----
**Any suggestion will be truly appreciated.**
Thanks

**Comment by Trinetra-MSFT** [comment]
@Harshul9089 , There is `onReactionsAddedAsync `method which catches the reactions added by user to any message. You will get the type of reaction added to messages in messageReaction object. 

```
   protected override async Task OnReactionsAddedAsync(IList<MessageReaction> messageReactions, ITurnContext<IMessageReactionActivity> turnContext, CancellationToken cancellationToken)
        {
    //Your logic to handle message reactions
        }
```
![image](https://user-images.githubusercontent.com/50989436/80338182-5c595480-8879-11ea-8753-b28693eb5253.png)

You can also fetch the message Id, conversation id & user name through turnContext.Activity object itself.
![image](https://user-images.githubusercontent.com/50989436/80338004-ebb23800-8878-11ea-90e9-72ce5185ac83.png)
Please take a look at [message reaction](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/25.message-reaction) github sample code

Let me know if this is not what you are looking for.

**Comment by Harshul9089** [comment]
@Trinetra-MSFT Yes, I was searching for the exact thing. Thank you.
