### ISSUE TITLE
Teams search app is not behaving as expected in IOS

### ISSUE THREAD

**Issue by tekbird** [OfficeDev/BotBuilder-MicrosoftTeams#239]
When the app is loaded, user is presented with default items. After that if user enters some characters, the app does a search and presents the results correctly. The issue is when the user clicks on x button on the search input textbox, which should have brought the initial default items back. But it is not so, the app clears the result items, but not showing the default items from the initial run.

**Comment by Trinetra-MSFT** [comment]
@tekbird , Could you please share the repro steps or screenshots would be fine?

**Comment by tekbird** [comment]
The first one is the search results with x button in the texbox. the second one shows the empty result after clicking x button.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/678518/86250380-cad7cd00-bbb0-11ea-830f-fb57ce33728c.png)

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/678518/86250378-c9a6a000-bbb0-11ea-933a-f617316ed3d7.png)

**Comment by Trinetra-MSFT** [comment]
@tekbird ,  That is the expected behavior, Please see the attached screenshot for iOS mobile device.

Searching with Keyword:
![image](https://user-images.githubusercontent.com/50989436/91257754-51abbf00-e788-11ea-9e95-6d9b5a89e91a.png)

After clicking on X button it clear the search
![image](https://user-images.githubusercontent.com/50989436/91257822-7869f580-e788-11ea-976e-fb17c46a70a2.png)

**Comment by tekbird** [comment]
@Trinetra-MSFT, so is this an expected behaviour only in IOS? Because, it works correctly in Android (there is no x button on the textbox, but if I press backspace and clear the textbox, the initial results are brought back)

**Comment by Trinetra-MSFT** [comment]
@tekbird , Yes , once you type the text in search bar you will be able to see the cross button and result will be loaded, for iOS search is loaded based on text. Closing this thread. Please feel free to reopen if you have further query.
