### ISSUE TITLE
Teams search app on mobile device requires sign-in/out for changes to take effect

### ISSUE THREAD

**Issue by tekbird** [OfficeDev/BotBuilder-MicrosoftTeams#240]
I have observed that any changes made to a Teams app on desktop version of Teams (like removing, adding) requires the mobile app to sign out and sign in to take effect. It makes difficult updating the apps as users have to be instructed to logoff/login from mobile devices.

**Comment by Nikitha-MSFT** [comment]
This is the behaviour right now. Any changes done in desktop takes some time to show on mobile. We are working on making this experience better.
