### ISSUE TITLE
Teams search app not working with AdaptiveCard

### ISSUE THREAD

**Issue by tekbird** [OfficeDev/BotBuilder-MicrosoftTeams#241]
I have a MS Teams search app which works fine with ThumbnailCard. But when I switched to AdaptiveCard, it no longer works.

Following is my response JSON:

`{
   "composeExtension":{
      "type":"result",
      "attachmentLayout":"list",
      "attachments":[
         {
            "contentType":"application/vnd.microsoft.card.adaptive",
            "content":{
               "type":"AdaptiveCard",
               "version":"1.0",
               "body":[
                  {
                     "type":"Container",
                     "items":[
                        {
                           "type":"TextBlock",
                           "size":"medium",
                           "weight":"bolder",
                           "text":"Publish Adaptive Card schema"
                        },
                        {
                           "type":"ColumnSet",
                           "columns":[
                              {
                                 "type":"Column",
                                 "width":"auto",
                                 "items":[
                                    {
                                       "type":"Image",
                                       "size":"small",
                                       "style":"person",
                                       "url":"https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                                    }
                                 ]
                              },
                              {
                                 "type":"Column",
                                 "width":"stretch",
                                 "items":[
                                    {
                                       "type":"TextBlock",
                                       "weight":"bolder",
                                       "text":"Matt Hidinger",
                                       "wrap":true
                                    },
                                    {
                                       "type":"TextBlock",
                                       "isSubtle":true,
                                       "text":"Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
                                       "wrap":true,
                                       "spacing":"none"
                                    }
                                 ]
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "type":"Container",
                     "items":[
                        {
                           "type":"TextBlock",
                           "text":"Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
                           "wrap":true
                        },
                        {
                           "type":"FactSet",
                           "facts":[
                              {
                                 "title":"Board:",
                                 "value":"Adaptive Card"
                              },
                              {
                                 "title":"List:",
                                 "value":"Backlog"
                              },
                              {
                                 "title":"Assigned to:",
                                 "value":"Matt Hidinger"
                              },
                              {
                                 "title":"Due date:",
                                 "value":"Not set"
                              }
                           ]
                        }
                     ]
                  }
               ],
               "actions":[
                  {
                     "type":"Action.ShowCard",
                     "card":{
                        "type":"AdaptiveCard",
                        "version":"1.0",
                        "body":[
                           {
                              "type":"Input.Date",
                              "id":"dueDate"
                           }
                        ],
                        "actions":[
                           {
                              "type":"Action.Submit",
                              "title":"OK"
                           }
                        ]
                     },
                     "title":"Set due date"
                  },
                  {
                     "type":"Action.ShowCard",
                     "card":{
                        "type":"AdaptiveCard",
                        "version":"1.0",
                        "body":[
                           {
                              "type":"Input.Text",
                              "id":"comment",
                              "placeholder":"Enter your comment",
                              "isMultiline":true
                           }
                        ],
                        "actions":[
                           {
                              "type":"Action.Submit",
                              "title":"OK"
                           }
                        ]
                     },
                     "title":"Comment"
                  }
               ],
               "$schema":"http://adaptivecards.io/schemas/adaptive-card.json"
            }
         }
      ]
   }
}`

Upon opening the app, it tries to load initial items, and throws error `Something went wrong. Please try again.`.

Upon checking the Teams log (CNTRL+ALT+SHIFT+1), it has the following items, which I believe belong to this error:

`2020-06-29T12:37:04.951Z Err	InputExtensionViewModel: Failed to complete command request for loadDefaultItems. Error: Invalid invoke response: Missing title or text in preview content for list layout
2020-06-29T12:37:04.951Z Inf	[Scenario]ext_runCommand_inputextension [step](1)stop (1373ms/1374ms)
2020-06-29T12:37:04.950Z Err	InputExtensionService: Input extension invoke command failed
2020-06-29T12:37:04.950Z Err	Unhandled exception. Error: Invalid invoke response: Missing title or text in preview content for list layout, cause: , stack: new t@https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-4d5c5bd.js:3:520214 > {anonymous}()@https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-4d5c5bd.js:3:542137 > c@https://statics.teams.cdn.office.net/hashedjs/lazy-ng1-mod-experience-container-services.min-9ac2632.js:1:39905 > Function.Do@https://statics.teams.cdn.office.net/hashedjs/lazy-ng1-mod-experience-contain...`

**Comment by Abhijit-MSFT** [comment]
@tekbird, CompsoeExtension.attachementLayout does not support adaptive card. Check this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#respond-to-user-requests) for more details.
