### ISSUE TITLE
Teams search app not loading further pages

### ISSUE THREAD

**Issue by tekbird** [OfficeDev/BotBuilder-MicrosoftTeams#242]
We have a teams search app that pulls data from an internal system. Initially, the app was developed using `Thumbnail card`. Using this, the app loads further pages after initial page on page scroll. but after migrating to `Office 365 Connector card`, the app only loads first page.

**Comment by Trinetra-MSFT** [comment]
@tekbird , Could you please look at [Notes on office 365 connector cards](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#notes-on-the-office-365-connector-card)?

**Comment by tekbird** [comment]
@Trinetra-MSFT, I read the section you suggested, but it does not say about this kind of limit. Could you please provide a direct reference to that? or a screenshot would be fine.

**Comment by Trinetra-MSFT** [comment]
@tekbird , Sorry for the delayed response, could you please share your app manifest with us?

**Comment by tekbird** [comment]
@Trinetra-MSFT, Please find the manifest below. Please note that some specific data has been removed (marked as xxxx). If you need the whole info, please share your email address:

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "1.1",
  "id": "xxxxxxxx",
  "packageName": "com.xxxx.xxxx.searchExtension",
  "developer": {
    "name": "xxxxxxx",
    "websiteUrl": "xxxxx",
    "privacyUrl": "xxxxxxx",
    "termsOfUseUrl": "xxxxxxx"
  },
  "name": {
    "short": "Synergy 365 Integration search",
    "full": "Synergy 365 Integration search"
  },
  "description": {
    "short": "Synergy 365 Integration search for Exact Synergy",
    "full": "Synergy 365 Integration search offers the possibility to search for accounts, documents, items, projects and requests from Exact Enterprise Synergy to included as hyperlink in a chats"
  },
  "icons": {
    "outline": "Synergy-365-Integration-outerline.png",
    "color": "Synergy-365-Integration-logo.png"
  },
  "accentColor": "#abcdef",
  "composeExtensions": [
    {
      "botId": "xxxxx",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "searchQuery",
          "context": [ "compose" ],
          "description": "xxxxxxxxxxx Integration search",
          "title": "Search",
          "type": "query",
          "initialRun": true,
          "parameters": [
            {
              "name": "searchQuery",
              "title": "Search Query",
              "description": "Search Query",
              "inputType": "text"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Trinetra-MSFT** [comment]
@tekbird , We need the Bot id as well to test this issue you can reachout to `microsoftteamsdev@microsoft.com` alias with your actual manifest & close the issue here.

**Comment by tekbird** [comment]
An email has been sent with a reference to this ticket.

**Comment by Trinetra-MSFT** [comment]
Closing this issue, will be tracking it over Email.
