### ISSUE TITLE
How to post MessageCard JSON Payload on Teams to user in C#

### ISSUE THREAD

**Issue by rrc2k4** [OfficeDev/BotBuilder-MicrosoftTeams#243]
I have a messagecard json payload and have to post to the user from bot using bot framework.  how can i post that content? should it be sent as attachment and content parameter set to json payload and what should be content type for that attachment. 
Please suggest.

**Comment by aosolis** [comment]
Here's an example: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#example-office-365-connector-card

**Comment by rrc2k4** [comment]
Thanks for the details. It helped.
