### ISSUE TITLE
After Click on Allow it is showing Error.Login Consent is not Working in the Teams Desktop and in Browser.

### ISSUE THREAD

**Issue by TejaReddy0226** [OfficeDev/BotBuilder-MicrosoftTeams#245]
After Click on Allow it is showing Error.Login Consent is not Working in the Teams Desktop and in Browser.
![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/62458014/89261014-f552f500-d64a-11ea-970a-372e2930e01a.png)

**Comment by Nikitha-MSFT** [comment]
No, You cannot get images from teams.microsoft.com. Also the images which you have given in the adaptivecard should be publicly available. For more information could you please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images)?

**Comment by Nikitha-MSFT** [comment]
Which Document are you following? Could you please share repro steps? Also could you please share request body?
