### ISSUE TITLE
[Dev Issue]The `theme` parameter in the request of `handleTeamsMessagingExtensionConfigurationQuerySettingUrl` is missing?

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/BotBuilder-MicrosoftTeams#246]
Hi Team,

Recently we found that:
The `theme` parameter in the request of `handleTeamsMessagingExtensionConfigurationQuerySettingUrl` is missing.

As we know, it is existing before. Is this a new change for Teams?

Thanks!

**Comment by Gousia-MSFT** [comment]
Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/1957.
