### ISSUE TITLE
TextInput is not passing value to HttpPost action in Teams

### ISSUE THREAD

**Issue by k343497** [OfficeDev/BotBuilder-MicrosoftTeams#247]
Dear all,

I am using Webhooks Connector in MS Teams, and call API to send 365 connectors MessageCard.

Here is my MessageCard JSON
`{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "summary": "summary",
    "themeColor": "0076D7",
    "title": "Testing MessageCard",
    "sections": [
        {
            "activityTitle": "![TestImage](https://47a92947.ngrok.io/Content/Images/default.png)",
            "activitySubtitle": "Testing MessageCard Send Email",
            "facts": [
                {
                    "name": "Total Found:",
                    "value": "0"
                }
            ],
            "text": "This is the text."
        }
    ],
    "potentialAction": [
        {
            "@type": "ActionCard",
            "name": "Feedback",
            "inputs": [
                {
                    "@type": "TextInput",
                    "id": "feedback",
                    "isMultiline": true,
                    "title": "Give me some feedback of this alerting."
                }
            ],
            "actions": [
                {
                    "@type": "HttpPOST",
                    "body": "{\"methodType\" : \"SendEmail\", \"comment\" : \" {{feedback.value}}\"}",
                    "name": "SendEmail",
                    "bodyContentType": "application/json",
                    "target": "Logic APP endpoint",
                    "headers": [
                        {
                            "name": "Authorization",
                            "value": ""
                        }
                    ]
                }
            ]
        }
    ]
}`

My logic App is set up like :
![image](https://user-images.githubusercontent.com/22550212/89874285-379da880-dbee-11ea-9bd4-b1c608c448f3.png)

But when I received the email, the content is empty:
![S__3817478](https://user-images.githubusercontent.com/22550212/89874839-fa85e600-dbee-11ea-8810-a2b70c63ff8c.jpg)

However, if I use the same JSON to test with message [Card Play Ground](https://messagecardplayground.azurewebsites.net/)

The result gives me the value I type in the text box:

![image](https://user-images.githubusercontent.com/22550212/89875075-56e90580-dbef-11ea-86bc-b6a17b912a68.png)

Please advice. Thank you.

**Comment by Trinetra-MSFT** [comment]
@k343497, Could you please check this [sample code](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Utils/TaskHelper.cs) for connector? Also could you please confirm if you have  enabled actions in connector developer dashboard?

**Comment by k343497** [comment]
Thank you, I found out the problem is. Thank you for your help
