### ISSUE TITLE
Teams search app not loading initial items on IOS

### ISSUE THREAD

**Issue by tekbird** [OfficeDev/BotBuilder-MicrosoftTeams#248]
After starts using the card type "application/vnd.microsoft.teams.card.o365connector", on IOS (tested on XR), the initial items won't be displayed. I see it tries to load and indeed hits the backend service, but the results will not get displayed.

I also checked the Azure Devops app and it behaves the same.

Is there a setting to be turned on, or is it an expected behaviour (on Android, it works perfect)?

**Comment by Trinetra-MSFT** [comment]
@tekbird , That is the expected behavior, iOS teams messaging extension search load the pages on demand. We have the same behavior for azure devOps too. Once you type in search text it will load the result.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you further query.
