### ISSUE TITLE
Bot rate limits update

### ISSUE THREAD

**Issue by vitaliishandra** [OfficeDev/BotBuilder-MicrosoftTeams#252]
There was the rate limit of 15000 messages/bot/all tenants. Currently this limitation is removed from the official documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit 
Is this limit still applied?

**Comment by Abhijit-MSFT** [comment]
Yes, this component is removed. Now there is no limit of 15k.
