### ISSUE TITLE
Adaptive Card Action.Submit is not working on MS Team on iOS as expected

### ISSUE THREAD

**Issue by ikivanc** [OfficeDev/BotBuilder-MicrosoftTeams#253]
Hi team, 

I've implemented an adaptive card (v 1.3) to retrieve `Input.Text`, `Input.Date` and `Input.Time` values on MS Team using BotFramework (v4.12.2)

I've added `msteam` to my data with a Bot Framework action. It works on Microsoft Teams on PC but it's not working on Microsoft Teams on Mobile. Please see below screenshots

It's working as expected on MS Team on PC,
![image](https://user-images.githubusercontent.com/118657/114403821-cadc1300-9bad-11eb-81d1-5986868b2020.png)

However it's not retrieving data on MS Teams on iOS Mobile
![image](https://user-images.githubusercontent.com/118657/114403695-b0a23500-9bad-11eb-94d1-327b58648e9d.png)

This is my adaptive card template:
```json
 {
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "medium",
      "weight": "bolder",
      "text": "Predict Workout"
    },
    {
      "type": "Input.Text",
      "value": "Istanbul",
      "id": "cityInput"
    },
    {
      "type": "Input.Date",
      "id": "dateInput"
    },
    {
      "type": "Input.Time",
      "id": "timeInput",
      "value": "08:00"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Predict",
      "id": "predictButton",
      "style": "positive",
      "data": {
        "msteams": {
          "type": "messageBack",
          "displayText": "Predict workout display",
          "text": "Predict workout text",
          "value": "{\"cityInput\": \"${cityInput}\", \"dateInput\": \"${dateInput}\", \"timeInput\": \"${timeInput}\"}"
        }
      }
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3"
}

```
Is it possible to guide me to solve this issue?

Thanks.

**Comment by Prasad-MSFT** [comment]
Hi @ikivanc ,
We tried to repro the issue as you mentioned and are facing the same issue in iOS. Its working fine in Desktop client and Android devices. We have raised a bug for this issue and concerned team is looking into it. We will inform you once we get further update. Thanks!

**Comment by Prasad-MSFT** [comment]
The issue seems to be fixed. Please do verify.
Thanks!
