### ISSUE TITLE
Section's 'startGroup' not working in Teams

### ISSUE THREAD

**Issue by lzanatta** [OfficeDev/BotBuilder-MicrosoftTeams#256]
Hi,

I'm working on sending some messages to MS Teams using O365 connectors and the Actionable Message Card format.
Following the documentation [here](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#section-fields) it says that one can use the 'startGroup' property to control whether a separator should be rendered between elements, but that does not seem to be working:

My message:
```
{
  "@type": "MessageCard",
  "@context": "https://schema.org/extensions",
  "summary": "Summary",
  "sections": [
    {
      "text": "Some text"
    },
    {
      "startGroup": false,
      "text": "Another text"
    },
    {
      "startGroup": true,
      "text": "Yet another text"
    }
  ]
}
```

My message rendered in Teams (very faint but visible horizontal lines between each text block):

![screen](https://user-images.githubusercontent.com/46678005/125622545-c9d65d4a-b35c-4969-8ab1-a745944121aa.jpg)

Expected result (created using the [message card playground](https://messagecardplayground.azurewebsites.net/) - only one horizontal line between the second and third text block)

![screen_alt](https://user-images.githubusercontent.com/46678005/125623173-baac5d86-6da2-4235-a04e-ac95d42f6679.jpg)

Am I using it wrong or is this a problem with how Teams renders the cards?

Thanks for the help!

**Comment by HunaidHanfee-MSFT** [comment]
Hello, We are able to repro this issue. We will get back to you once we got clarification with internal team.

Thanks.

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
Please refer this - [Types of Cards -> Office 365 connector card -> Additional information](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#additional-information-on-the-office-365-connector-card) 
Its mention 

> startGroup always treated as true in Teams

Thanks.
