### ISSUE TITLE
Accessbility issue :- Need Alt attribute in O365ConnectorCardSection class

### ISSUE THREAD

**Issue by MayurMundekar** [OfficeDev/BotBuilder-MicrosoftTeams#264]
Hi Team, 
We are facing accessibility issue when the card is creating using O365ConnectorCardSection . Because  along with ActivityImage property we don't have Alt property for them. so when we are rendering that card and do accessibility check we are getting issue. Please find the attachment for reference. 
If we can add alt property O365ConnectorCardSection this issue will resolved. Please help us .

<img width="627" alt="2021-08-05 10_31_06-Prod-Bot (Team for Mayur (ADO chatops)) _ Microsoft Teams" src="https://user-images.githubusercontent.com/83640993/128293706-79a96ddd-d73a-4176-8113-4b21f23ab26c.png">
[Issue Details.txt](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/files/6936027/Issue.Details.txt)

**Comment by ChetanSharma-msft** [comment]
@MayurMundekar - Sorry for the delay.
Is it resolved or still looking for any help?

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share the O365 Card body and repro steps. Could you also explain the issue  in details.

**Comment by HunaidHanfee-MSFT** [comment]
Please let us know if you have any query, we are closing this from our side.

**Comment by ghost** [comment]
### Tell us about your experience! 

Hi MayurMundekar! This issue is closed in our system. We would like your [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback). 

Best regards, 
Teams Platform
