### ISSUE TITLE
Invocation of adaptive card or custom form works fine on Teams Desktop App but not in Mobile App(iOS)

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [OfficeDev/BotBuilder-MicrosoftTeams#268]
I have used the TeamsTaskModule sample from the Bot Builder SDK sample. It displays the adaptive card with 3 options as below:
![image](https://user-images.githubusercontent.com/5042316/174198921-4890b814-0055-4046-ab31-963f6d788b56.png)

and ,clicking adaptive card button works fine on the Desktop app but not in Web App (Edge).

**Comment by Nivedipa-MSFT** [comment]
@SonOfJesseAsSnekithan - We have tested the TeamsTaskModule sample. We have checked in Edge browser but it was working fine at our end.
Could you please share the console logs to investigate further?

**Comment by SonOfJesseAsSnekithan** [comment]
Sorry for the late response, it works in desktop/web app, but not in the iOS App where clicking custom form  gives error message, something went wrong we can not open the app right now. 
![TaskModuleInvocationSampleApp](https://user-images.githubusercontent.com/5042316/175665767-d6e6cbb3-b2c3-4c76-bd1a-9e3ba7b8984d.PNG)
![TaskModuleInvocationIssue1](https://user-images.githubusercontent.com/5042316/175665785-a7456b60-5e82-4cc5-b017-fa4acaf70e22.jpg)
#

**Comment by SonOfJesseAsSnekithan** [comment]
It works fine now. Few things I did : (1) approve the app in teams tenant for iOS teams client to work, side loading the app is enough for desktop client. (2) updated the teams app.

**Comment by Nivedipa-MSFT** [comment]
@SonOfJesseAsSnekithan - Glad to hear that its working at your end.
We are closing this issue, please feel free to reopen it, if required.
