### ISSUE TITLE
Teams Bot Node.js - send a proactive message to a particular person that is not part of conversation but has app installed? 

### ISSUE THREAD

**Issue by sanasz91mdev** [OfficeDev/BotBuilder-MicrosoftTeams#279]
Hello

how can i send a proactive message to a particular person that is not part of conversation but has app installed. all i have is that person's email address. can teams bot application send him/her a proactive message by just knowing email address?

p.s. I don't want any storage to be associated with my bot.

**Comment by Prasad-MSFT** [comment]
@sanasz91mdev - To send a proactive message to a user, a group chat, or a team, your bot must have the requisite access to send the message. For a group chat or team, the app that contains your bot must be first installed in that location.

FYI, Teams doesn't support sending proactive messages using email or User Principal Name (UPN).

Please refer: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet
