### ISSUE TITLE
Invalid declaration of ComposeExtensionHandlerType

### ISSUE THREAD

**Issue by wictorwilen** [OfficeDev/BotBuilder-MicrosoftTeams#46]
Shouldn't the following export be changed as follows. Since `Error` is not a nullable type you always have to send an error?

Current implementation
``` TypeScript
export type ComposeExtensionHandlerType = 
  (event: builder.IEvent, query: ComposeExtensionQuery, 
  callback: (err: Error, result: IComposeExtensionResponse, statusCode?: number) 
    => void) => void;
```

Recommended:
``` TypeScript
export type ComposeExtensionHandlerType = 
  (event: builder.IEvent, query: ComposeExtensionQuery, 
  callback: (err: Error | null, result: IComposeExtensionResponse, statusCode?: number) 
    => void) => void;
```

Current implementation gives the following TypeScript error when transpiling `callback(null, ...)`: `error TS2345: Argument of type 'null' is not assignable to parameter of type 'Error'.`

**Comment by RamjotSingh** [comment]
@BillZengMSFT Can you take a look here?

**Comment by BillZengMSFT** [comment]
Hi @wictorwilen  I think this link explains well https://github.com/Microsoft/TypeScript/issues/8322

> Quick background, if you are not using --strictNullChecks both null and undefined are in the domain of all types. so T | undefined | null is equivalent to T. if you are using --strictNullChecks however, that is not the case. T does not include null or undefined.
