### ISSUE TITLE
starting a new thread everytime the proactive dialog is started

### ISSUE THREAD

**Issue by brijrajsingh** [OfficeDev/BotBuilder-MicrosoftTeams#50]
I have a MS Teams bot that records the conversations happening in a group conversation. But of course I am aware that the MS teams bots can't do the group conversations as of now. The conversations need to mention the bot in order to record the conversation and I am recording the conversations in a documentdb document.

I need to push new conversation topics using a proactive dialog, all nice and fine but everytime I push a msg it lands in the same thread.

Is there a way to make sure everytime a new dialog is invoked it starts a new thread.

This is how I start a new dialog

```
// initiate a dialog proactively 
function startProactiveDialog(address,txid,imageurl,textblurb) {
    console.log(txid); 
    bot.beginDialog(address, "*:/conversationRecorder",[txid,imageurl,textblurb]);  
}

```

**Comment by RamjotSingh** [comment]
No there is no way of creating a new direct conversation between a user and a bot. Only one such unique conversation can exist. So even if you call create conversation multiple times it will always return the same conversation.
