### ISSUE TITLE
Unable to serialize `ComposeExtensionAttachment`

### ISSUE THREAD

**Issue by jpoon** [OfficeDev/BotBuilder-MicrosoftTeams#52]
### Repro
1. Run any sample C# app that uses `ToComposeExtensionAttachment()` extension method (e.g. https://github.com/OfficeDev/microsoft-teams-sample-get-started/blob/master/CSharp/TeamsToDoApp/Compose/ComposeExtension.cs). 
2. Serialization of https://github.com/OfficeDev/microsoft-teams-sample-get-started/blob/master/CSharp/TeamsToDoApp/Compose/ComposeExtension.cs#L75 blows up with the following error:

```
Self referencing loop detected for property 'preview' with type 'Microsoft.Bot.Connector.Attachment`
```

### Cause
I suspect the cause of this issue is https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/AttachmentExtensions.cs#L60. If `previewAttachment` is null which is the default, it references itself and this eventually will blow up on JSON serialization.

### Workaround
Don't use the extension method
```
                var composeExtensionAttachment = new ComposeExtensionAttachment
                {
                    Content = attachment.Content,
                    ContentType = attachment.ContentType,
                    ContentUrl = attachment.ContentUrl,
                    Name = attachment.Name,
                    ThumbnailUrl = attachment.ThumbnailUrl,
                };
```

Using https://www.nuget.org/packages/Microsoft.Bot.Connector.Teams/0.5.6 but looking through the commit history, I suspect this issue has been there since the feature was introduced.

**Comment by RamjotSingh** [comment]
This should be fixed in the latest release nuget. Please reopen if this is not the case.
