### ISSUE TITLE
[Question] Is there a way to get the aadObjectId?

### ISSUE THREAD

**Issue by santiagodoldan** [OfficeDev/BotBuilder-MicrosoftTeams#73]
I want to add a link in one email to let users access the 1:1 chat without having to search the private chat manually, the URL looks like `https://teams.microsoft.com/_#/conversations/19:(aadObjectId_here)_(bot_id_here)@unq.gbl.spaces?ctx=chat`. Is there a way or an endpoint to get that info? or can I build a different URL without the `aadObjectId` and access the 1:1 chat?

Thanks

**Comment by RamjotSingh** [comment]
You can call GetTeamsConversationMembersAsync which gives full profile for the user. This has AAD Object ID in it.

**Comment by aosolis** [comment]
@santiagodoldan Try using the deeplink to a chat:
https://teams.microsoft.com/l/chat/0/0?users=28:<bot_id>

**Comment by santiagodoldan** [comment]
Deeplink works even better, they can choose to use the native app right there, thanks
