### ISSUE TITLE
[CSharp] How to mention to channel

### ISSUE THREAD

**Issue by yuimam** [OfficeDev/BotBuilder-MicrosoftTeams#76]
I'd like to ask about how to mention to channel or team in Microsoft Teams from Bot.
The following document says that such a type of mention is not supported.
 
https://docs.microsoft.com/ja-jp/microsoftteams/platform/scenarios/bots-channel-conversations#mentions

“At this time, team and channel mentions are not supported.”
 
Is it not supported even now?
And do you have any plan to support this?
 
I'd like to make it possible to notify all of the members in a teams channel from Bot.

**Comment by Wajeed-msft** [comment]
@yuimam - Team and channel mentions are still not supported. Documentation for this will be updated once this feature is enabled (ETA March 2018).
