### ISSUE TITLE
fetchMembers does not return all the users for different channels of the same team

### ISSUE THREAD

**Issue by santiagodoldan** [OfficeDev/BotBuilder-MicrosoftTeams#80]
One of our accounts started a customer request saying that some users didn't get a message from our bot, after doing some researches I noticed that 2 channels of the same team were returning different users (we're using `fetchMembers`) is there a reason why 2 channels of the same team have more/less users? not sure if a user can change a configuration to not appear there.

I asked this user to remove one of the missing users from the team and then re-add the user, after one hour the user started appearing using `fetchMembers`, but only that user, this channel has other 4 users that still don't appear, maybe this is helpful to detect the issue.

Thanks

**Comment by jotrick** [comment]
I'm guessing this issue is happening for you because you are using the channel.id to fetch the member list rather than that team.id to fetch the member list. Using the team.id should return the whole team's member list no matter the channel. Using the channel.id gives you a list of members that is formulaically figured out based on things like who has commented in this channel, who has favorited this channel, who was at-mentioned in this channel, etc.

**Comment by santiagodoldan** [comment]
@jotrick thanks, you're correct, passing the team.id returns the whole list of users.

The problem is that we don't have the team.id in some scenarios, shouldn't always return the same list given the channel.id anyway?

**Comment by aosolis** [comment]
@santiagodoldan To clarify, what are scenarios where you have channel.id but not team.id? Is this one where you've cached the channel id but not the team id? Messages sent to your bot in a team context should always have both team and channel id in its channelData.

**Comment by santiagodoldan** [comment]
@aosolis yes, our bot runs a scheduled job and tries to get the list of members based on checkins stored in the DB, some of them do not have a team id.

Are there any plans on implementing a new endpoint to get a list of team ids given a tenant?

**Comment by RamjotSingh** [comment]
@billbliss to answer the question above.

**Comment by santiagodoldan** [comment]
@bilby91 thanks for that.

Going back to my previous issue, I'm thinking if it could be a good idea to document what @jotrick mentioned, I mean this part `Using the channel.id gives you a list of members that is formulaically figured out based on things like who has commented in this channel, who has favorited this channel, who was at-mentioned in this channel, etc.` because I'd expect a list having ALL users if I don't know that.
