### ISSUE TITLE
Bump ms-rest

### ISSUE THREAD

**Issue by bilby91** [OfficeDev/BotBuilder-MicrosoftTeams#81]
Would it be possible to bump `ms-rest` to the latest version ? Current one is using request 2.74 that uses a deprecated version of `uuid` (node-uuid) ?

**Comment by RamjotSingh** [comment]
@BillZengMSFT Please take a look.

**Comment by bilby91** [comment]
@RamjotSingh @BillZengMSFT Created PR (#82 )

**Comment by bilby91** [comment]
Any updates ?

**Comment by billbliss** [comment]
Thanks for the submission @bilby91, and apologies for the delay in accepting it.
