### ISSUE TITLE
Get teams a bot belongs to

### ISSUE THREAD

**Issue by bilby91** [OfficeDev/BotBuilder-MicrosoftTeams#83]
We having some complications in our application because we didn't cache all the team ids for the accounts that were created with our bot. We think it would be a really good idea to add an endpoint for getting the teams inside a tenant that a user belongs to.

Is this in the pipeline ? If not, could it be possible to add ? 

I'm also aware of other people having similar issues with this as well.

**Comment by RamjotSingh** [comment]
@billbliss

**Comment by billbliss** [comment]
Yes, we agree - this is a problem that others have reported. We are currently investigating an overhaul of how bots are registered including this.

**Comment by bilby91** [comment]
@billbliss Thanks for the reply!

Any ETA for this change on bot registration ?

**Comment by bilby91** [comment]
Any updates on this ?

**Comment by santiagodoldan** [comment]
@billbliss could you please give us a ETA? we'd love to fix some inconsistencies in our db with this fix. thanks :)

**Comment by bilby91** [comment]
@billbliss @BillZengMSFT I found this in the Microsoft Graph documentation (https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_list_joinedteams)

I'm wondering if this could be used in the context of a bot so that we can solve our issue. 

Thanks before hand!

**Comment by billbliss** [comment]
I'm afraid not. Azure Active Directory doesn't know about bot "users" currently, so they don't appear in the membership list for a group/team.

**Comment by bilby91** [comment]
@billbliss mmm, sad :(

Any progress with having this feature for bots ?

**Comment by bilby91** [comment]
@billbliss Another option that might works for us is if we could privately send the list of tenants that we need that data. Could that be possible at least ? We need to fix some old accounts data.
