### ISSUE TITLE
fetchMembers returns guest users with neither a name nor an email

### ISSUE THREAD

**Issue by santiagodoldan** [OfficeDev/BotBuilder-MicrosoftTeams#88]
Hello guys, I've found one thing today playing with Guest users, when a tenant invites a guest user, `fetchMembers` returns the user with neither a name nor an email, but when that user accepts the invitation, then `fetchMembers` includes the name and email.

**Comment by RamjotSingh** [comment]
@punpuny Can you take a look at this?

**Comment by BillZengMSFT** [comment]
Will fix this thanks!

**Comment by BillZengMSFT** [comment]
After investigation, we can't reproduce the issue. Will close.

**Comment by bilby91** [comment]
We are still able to reproduce this problem. 

They key aspect to reproduce the problem is that the guest user doesn't have to login into teams after being invited. When this happen, the user is returned in the API but without name or email. Once the user has logged in at least one time, the data starts flowing correctly. I think that the correct behaviour should be:

1) Don't send the user at all if it has not logged in.

or

2) Send email and name always.

Can you confirm you have tried what is described @BillZengMSFT ?

**Comment by BillZengMSFT** [comment]
Can you clarify the first step? Invite a user and the guest doesn’t login?

**Comment by bilby91** [comment]
Yes, sure. 

So, once you invite the guest user, the guest user needs to first login to the account he belongs to (not the account he has been invited). Then, to actually go into the account he has been invited, he needs to go to  the settings in the left bottom corner and switch accounts. If the guest user doesn't do this last step, email and name are empty when calling the api. 

Martín

**Comment by BillZengMSFT** [comment]
@bilby91 can you provide you thread id and tenant id please? We actually didn't login and can't reproduce the issue

**Comment by BillZengMSFT** [comment]
@bilby91 In your request, I am wondering if all of users in thread have empty email and name? Or some of users are empty?

**Comment by santiagodoldan** [comment]
@BillZengMSFT can I send those ids to billzeng808@gmail.com?

Regarding if all the other users have empty email and name, the only one is the guest that haven't accepted the invite yet.

**Comment by BillZengMSFT** [comment]
@santiagodoldan please send to zel@microsoft.com. Do you mean all users in thread get empty email and name?

**Comment by santiagodoldan** [comment]
@BillZengMSFT now it works ok 🤔 that's weird, but nice 😂 . I also created a new guest user and it worked ok too, now I can get  the user and email 👏  Thanks
