### ISSUE TITLE
GetTextWithoutMentions Exception with Microsoft.Bot.Connector v3.13.0.3

### ISSUE THREAD

**Issue by blfuentes** [OfficeDev/BotBuilder-MicrosoftTeams#91]
I update the Bot SDK to the latest version (3.13.0.3) and now whenever I try to use the method "GetTextWithoutMentions" I get the following exception:
`activity.Text = Connector.Teams.ActivityExtensions.GetTextWithoutMentions(activity);`
> Microsoft.Bot.Connector.Teams
> Method not found: 'System.Collections.Generic.IList`1<Microsoft.Bot.Connector.Entity> Microsoft.Bot.Connector.IMessageActivity.get_Entities()'.
>    at Microsoft.Bot.Connector.Teams.ActivityExtensions.GetTextWithoutMentions(IMessageActivity activity)
>    at Microsoft.Bot.Sample.LuisBot.MessagesController.<Post>d__0.MoveNext() in ...\Controllers\MessagesController.cs:line 36

The Class 'Activity' does contain a property `public IList<Entity> Entities { get; set; }`

Any idea about this?

Microsoft.Bot.Connector 3.13.0.3
Microsoft.Bot.Connector.Teams 0.8.0

**Comment by blfuentes** [comment]
Checking the github for Microsoft.Bot.Connector:
https://github.com/Microsoft/BotBuilder/pull/4123/files#diff-74a60cf62b5d3668919f15c196994fc0
In IMessageActivity `IList<Entity> Entities { get; set; } `was removed

**Comment by RamjotSingh** [comment]
We have engaged Bot Framework team and working on resolving this

**Comment by RamjotSingh** [comment]
I see that while the Entities were removed from IMessageActivity it was added to IActivity. So the code should not be throwing this error. Can you ensure that you indeed have the right nuget package? Please delete the cached package and restore again and try?

**Comment by aosolis** [comment]
I think moving a member from an interface to a base interface is a binary and source breaking change (see https://stackoverflow.com/questions/1456785/a-definitive-guide-to-api-breaking-changes-in-net). BotBuilder may have made a mistake doing this in a minor version update.

"Binary break is due to the fact that interface methods are fully qualified in generated IL for explicit implementations, and interface name there must also be exact."

**Comment by blfuentes** [comment]
@RamjotSingh Yes, I double checked it. I have all up to date packages and it still doesn't work.
As workaround I just created a local function using the same code `GetTextWithoutMentions` has and it works. So I would say it could be related to the interface change @aosolis commented.

**Comment by RamjotSingh** [comment]
Can you try updating to latest version of Bot.Builder https://www.nuget.org/packages/Microsoft.Bot.Builder/ I ran my tests and things seem to work fine.

**Comment by blfuentes** [comment]
Perfect, I updated to the last version and it works.
I see they added the Entities Colletion into the IMessageActivity
https://github.com/Microsoft/BotBuilder/commit/9baa58a42c6291644b263bf6efd864631a74cb7c#diff-74a60cf62b5d3668919f15c196994fc0
The issue can be closed.
