### ISSUE TITLE
nodemon dependency in botbuilder-teams

### ISSUE THREAD

**Issue by MarkHerhold** [OfficeDev/BotBuilder-MicrosoftTeams#96]
`nodemon` is defined as a dependency. It should probably be a dev dependency.
https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/Node/package.json#L16

**Comment by billbliss** [comment]
Good catch. Created a PR to move it: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/pull/99
