### ISSUE TITLE
[Question] Is it possible to load custom state without any access to context or activity?

### ISSUE THREAD

**Issue by ilanopat** [OfficeDev/BotBuilder-MicrosoftTeams#98]
I have an API controller that calls a class which messages the user for the notification I'm doing for my app. Is there any possible way to access the custom state if I'm not using Dialogs?

**Comment by RamjotSingh** [comment]
Not sure what you mean by custom state here. Are you talking about data stored in Bot State API? Or somewhere else?

**Comment by ilanopat** [comment]
Oh, sorry. I mean I implemented a custom state which saves the state on using sql.

**Comment by RamjotSingh** [comment]
Dialogs are one way to write bots and they work well with cases where users are sending messaging and you are responding to them, but not with proactive case (where server tries to initiate the conversation or take an action without user performing an action).

For these cases you can retrieve the data from your storage based on the key you stored it against and then create Activity yourself. You can then use instance of ConnectorClient class to send this activity (use ConnectorClient.Conversations.SendActivity).

As far as the data access is concerned you will have to check in Dialogs code to see how the data is getting stored (key, storage etc.) and then access it in non-Dialog code accordingly. Does this answer your question?

**Comment by ilanopat** [comment]
```
using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                {
                    var botDataStore = scope.Resolve<IBotDataStore<BotData>>();
                    var key = new Address(conversationReference.Bot.Id, conversationReference.ChannelId, conversationReference.User.Id, conversationReference.Conversation.Id, conversationReference.ServiceUrl);
                    var userData = await botDataStore.LoadAsync(key,BotStoreType.BotUserData, CancellationToken.None);
                    var client = new ConnectorClient(new Uri(conversationReference.ServiceUrl), GetAppCredentials(activity));
                                var message = conversationReference.GetPostToBotMessage();
message.Text = "Hello, this is a notification"
                                await client.Conversations.SendToConversationAsync(message, CancellationToken.None);
scope.Dispose();
}
```
like this?

**Comment by billbliss** [comment]
As Ramjot says, to post to a conversation (whether it's a chat or a channel) you need the ID of that conversation.

In our opinion it's too difficult to do "proactive messages" which is what we call it and we're looking to simplify it.

Taking a step back, what are you trying to do? The use case, that is?

**Comment by ilanopat** [comment]
Okay, I see, I'm using Azure SQL for the implementation of custom state, I have an API controller which can be triggered by third-party API, and then this API controller that I wrote calls another class which has a function to send a message to the user, my problem is when my API is called by the third-party API, I have no details of whom the bot is going to send the message to. The code from above only have the ConversationReference as a static variable.

**Comment by RamjotSingh** [comment]
If you want to send a proactive message at the very least you need these things :-
- Service Url
- User Id (From.Id) or ConversationId (For 1:1 you can use From.Id and call Create conversation with it to get the conversationId but for teams and channels conversation Id is a must).

How are you planning to send the proactive message though? For example what triggers it? How do you know which conversation (or user) you have to send the message to?

**Comment by ilanopat** [comment]
I had solved the issue, thank you. You can close this now, I'll just open a new issue if I encounter one.
